### ISSUE TITLE
Debug level

### ISSUE THREAD

**Issue by BigfootN** [Valloric/ycmd#1018]
Hello,

I am currently using atom as a client. I would like to know if it would be possible to set the debug level.
When I type I sometimes get a window `Still parsing file no completion yet`. I rarely get it, but it is quite annoying. I searched in the `default_settings.json` file, but didn't find anything.

Since everything seems to be working fine, and I know that this error shows itself when I ask _really_ to quickly for a completion, I don't really find it useful.

Thank you very much in advance.

**Comment by bstaletic** [comment]
There is a `log_level` option which is set to `info` by default. Possible values are `debug`, `info`, `warning`, `error` and `critical`.

However, this won't prevent ycmd from displaying the `Still parsing file...` message because it is actually an exception which bubbles up to the client. If you want to hide the message, you will have to do it in atom when handling server exceptions.

**Comment by BigfootN** [comment]
Thank you for your response.

I suppose not, but would you happen to know how to do this ?

Thank you in advance.

**Comment by bstaletic** [comment]
For the vim client (YouCompleteMe) there is a `HandleServerException` in `base_request.py`. I have no idea about the atom client.

**Comment by BigfootN** [comment]
Thank you very much for your answer and for your help.
