### ISSUE TITLE
Single server instance VS multiple.

### ISSUE THREAD

**Issue by hifall** [Valloric/ycmd#1059]
Hello, new to ycmd here. Looks like an awesome project!

Currently each client starts a server instance for queries. I wonder if this scales in the scenario where many (1000+) concurrent clients are present. In such a scenario, 1000+ server instances would be spawned. Doesn't seem to me like very resource efficient.

If so, is it possible to have one server instance handle many clients?

Thanks!

**Comment by hifall** [comment]
Just found this [943](https://github.com/Valloric/ycmd/issues/943). Seems this won't be implemented in the official release.

If I wanted to implement this myself, how significant would the effort be?

**Comment by micbou** [comment]
> If I wanted to implement this myself, how significant would the effort be?

I think this would require rewriting the server from scratch:
 - none of the semantic completers would work because they all assume that the files are on disk;
 - all identifiers would be shared between the clients which is probably not a desirable thing;
 - cache would almost always be invalidated and without cache, completion filtering and sorting (which is one of the main features of ycmd) on each character is not viable (see my answer below);
 - extracting identifiers from tag files won't work because the files are read on disk;
 - and probably other things I didn't think of.

> Also, how does completer cache get in the way of such a would-be implementation, as mentioned in 943?

The server is supposed to filter and sort completions each time the user is typing a character. Since querying the semantic engine to get completions can be a slow operation, the server caches the result. If the cache is always invalidated, not only this renders the cache useless but it may result in a bad experience where the user have to wait a long time between each typed character to see the completions.
