### ISSUE TITLE
Feature Request: add new ways to find compile flags for header files that don't have a sibling

### ISSUE THREAD

**Issue by Fabbi** [Valloric/ycmd#1063]
We wrote a bit about this in PR #1035 so I thought I'd make a feature request instead of hijacking the PR-thread.

Basically the Idea is to search for entries that include the header file and use their compile commands to parse the header file.

For context check the PR #1035 .

> I am also not sure what "search for the nearest source file in db" means.

this means that you search for the next source file that is nearest in the file hierarchy.
If you search for `/foo/bar/baz/asd.hpp` and find no `/foo/bar/baz/asd.c[pp]` and no file that includes this file, you search for a `/foo/bar/baz/*.c[pp]`, then `/foo/bar/*.c[pp]`, then `/foo/bar/**/*.c[pp]` and so on.. 

>Do you have an example that would look for a source file that includes the requested header?

I don't have a good example as every entry has the include flag `-I <...>/include`, so searching for `<...>/include/geometry/linesegment.hpp`  collects every entry and sorts them by "distance".
It obviously would be better if we could search for a file that actually `#include`'s the header file, but for that we'd need to build some sort of include-tree or something like that. 
A quick google yields [a way to find all #includes in a file with libclang](https://www.fun4jimmy.com/2013/05/01/finding-all-includes-in-a-file-using-libclang-and-python.html) that could be used?

**Comment by bstaletic** [comment]
Thanks for opening a feature request. This kind of feedback is what we expected to happen much earlier when we implemented the compilation database support.

Currently, ycmd does [this](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/cpp/flags.py#L678-L698) when getting flags from the compilation database.

For headers, it tries to find something that exists in the database (if the entry for the header itself doesn't exist), by looping over possible source extensions and substituting the header extension with it.

That is fine for codebases that have source and header files next to each other. If a codebase uses `include` and `src` directories to split the files, this heuristic will fail.

We could implement looking for any source file in parent directories, like it's mentioned in the spacemacs extra conf and explained by @Fabbi, but it feels as if this would cause more harm than good (be wrong more often than right). Note that I have not given this an in-depth analysis, so it is worth discussing this further.

As for finding a source file that includes the specific header, my concern is that this might be slow. Especially if some header isn't included directly in a sourcee file, but only in other headers.
The linked python script that uses the libclang python API could easily be written in C++, since we already have a `TranslationUnit` class.

Finally, [this](https://github.com/cquery-project/cquery/blob/b523aa928acf8ffb3de6b22c79db7366a9672489/src/project.cc#L774-L813) is how cquery deals with headers in compilation databases. The heauristics there uses [`ComputeGuessScore()`](https://github.com/cquery-project/cquery/blob/b523aa928acf8ffb3de6b22c79db7366a9672489/src/project.cc#L689-L725) helper function.

**Comment by Fabbi** [comment]
> We could implement looking for any source file in parent directories, like it's mentioned in the spacemacs extra conf and explained by @Fabbi, but it feels as if this would cause more harm than good (be wrong more often than right). Note that I have not given this an in-depth analysis, so it is worth discussing this further.

This would only be wrong if you have a source file with the same name in your tree that is completely unrelated to the header you are querying for.

The bigger issue will be finding flags for header-only files, though.

**Comment by bstaletic** [comment]
I think I got something wrong. If ycmd finds a header called `foo.h` but not a `foo.c` in the same directory, we should keep looking for `foo.c` in parent directories? My initial understanding was to look for *any* source file in the parent directory.

Header only libraries will be trickier. I see no way to discover that, for pybind11, `include/pybind11/numpy.h` is included in `tests/test_numpy_array.h`, unless we parse source files and look for includes. Though, there's always a local extra conf option.

**Comment by sam-lunt** [comment]
It seems to me that trying to determine *where* a header is included will be both expensive and non-deterministic. It's entirely possible that a header is included in multiple files, some or all of which use different compilation flags. Additionally, will only implementation files be checked, or will it recursively follow all includes for each implementation file? That could get expensive if done for every source file.

For my personal ycm_extra_conf.py, I had been checking for foo.cpp to correspond to foo.hpp (for all combinations of source/header extensions). If that failed, I checked for *any* source file in the same directory as the header file, but only if *all* the source files in the directory used the same flags. I think there is likely a better rule that this, however.

I think the one main issue is projects that lay out their code as `include/project/a/b/c/foo.hpp` and `src/a/b/c/foo.cpp`, since it is entirely possible that a file `src/a/b/d/foo.cpp` also exists and should not be paired with `foo.hpp`.

The other issue is header-only libraries, especially C++ libraries that use `.h` instead of `.hpp`/`.hh`, since there is no way to decide between using C or C++ as the language. For `.hpp`, etc, you could use some reasonable C++ defaults.

**Comment by bstaletic** [comment]
> It seems to me that trying to determine where a header is included will be both expensive and non-deterministic.

I agree with both claims here (and the rest of the paragraph).

> checking for foo.cpp to correspond to foo.hpp (for all combinations of source/header extensions).

So far, so good. Ycmd is doing that by default. At the time of writing that code, this seemed like a reasonable starting point and we were hoping for feedback from people like you. Shame that we had to make a breaking change to get people's attention.

>  If that failed, I checked for any source file in the same directory as the header file, but only if all the source files in the directory used the same flags.

That "but only..." part seems strange. Why not just take flags from an arbitrary file? Keep in mind that we're dealing with heuristics and that we'll never covering all possible cases. For weird cases there's always a local extra conf.

>  projects that lay out their code as include/project/a/b/c/foo.hpp and src/a/b/c/foo.cpp, since it is entirely possible that a file src/a/b/d/foo.cpp also exists and should not be paired with foo.hpp.

Example of that kind of library is Boost. Okay, why shouldn't `src/a/foo.cpp` be paired with `include/a/foo.h` or `include/project/a/foo.h`?

> The other issue is header-only libraries

Example: Pybind11, a ycmd dependency.
I don't see a reasonable way of figuring out the correct flags for those and not covering this case doesn't sound too bad.

**Comment by sam-lunt** [comment]
> That "but only..." part seems strange. Why not just take flags from an arbitrary file? Keep in mind that we're dealing with heuristics and that we'll never covering all possible cases. For weird cases there's always a local extra conf.

Yes, I think that's perfectly reasonable too. My thinking was that: 1, it would be unlikely for a directory to have multiple source files that each take different flags and, 2, it would be easier to get someone's attention when there were no flags (compared to subtly wrong flags).

That said, I think picking any source file from the same directory would be right almost all of the time (header files can't be too picky about what flags they are compiled with, since they can be compiled with a spectrum of flags, depending on who includes them).

> Example of that kind of library is Boost. Okay, why shouldn't src/a/foo.cpp be paired with include/a/foo.h or include/project/a/foo.h?

Sorry, I did a poor job explaining my concern. If we have a library "foobar" that has two files, `src/alpha.cpp` and `include/foobar/alpha.hpp`, we should definitely pair those two files together. The pitfall I was worried about would be if the library has sub-directories `beta` and `gamma`. If we are trying to find the flags for `include/foobar/beta/common.hpp`, there could be files `src/beta/common.cpp` and `src/gamma/common.cpp`. It might be wrong to use the flags `src/gamma/common.cpp`.

Still, similar to the above point, it seems unlikely to have different flags for the same project, and header files should probably be able to handle either set of flags anyway..

> I don't see a reasonable way of figuring out the correct flags for those and not covering this case doesn't sound too bad.

I think that's fair. One feature that would probably get it 95% of the way there would be some way to add flags using a vim command, since then you could quickly get syntax checking. Alternatively, if there are no flags, YCM could use the value of `syntax` to set the value for `-x`. That way, users could do `:set syntax=cpp` or `:set syntax=c` and get a lot of features (the main exception being include checking).

**Comment by bstaletic** [comment]
> 1, it would be unlikely for a directory to have multiple source files that each take different flags and, 2, it would be easier to get someone's attention when there were no flags (compared to subtly wrong flags).

Both of those points have merits. My thinking was that it might be slow to check every file, potentially multiple times.

> (header files can't be too picky about what flags they are compiled with, since they can be compiled with a spectrum of flags, depending on who includes them).

That's true. That's why header only libs usually work with generic flags, like `['-std=c++11']`.
That's also an argument why the first file that includes the header would usually have the right flags and lexicographic order of file parsing would provide deterministic behaviour.

> Pairing include/foo/bar.h and src/bar.c

Okay, so we should be careful about parent directories we pair. How about this:
For any given `src/foo/bar/baz.c` a header can be found in:
- `include/project/foo/bar/baz.h` or
- `include/foo/bar/baz.h`

Of course, in actual code, the pairing would go in opposite direction.

> Header only

All of those proposed solutions are not only YCM specific, but Vim specific as well. Ycmd as a server is client agnostic. You can't expect ycmd-emacs to emulate vim features.

**Comment by sam-lunt** [comment]
> My thinking was that it might be slow to check every file, potentially multiple times.

I agree, I think a slowdown from checking each file is more likely than having different flags for files in the same directory.

> That's also an argument why the first file that includes the header would usually have the right flags and lexicographic order of file parsing would provide deterministic behaviour.

After this discussion, I would say I agree with this. My only question would be the cost of finding the first file to include it. In the worst case, it would require running the parsing each file in the directory, which could be expensive if there is a lot of files or the files are large.

I agree with your metric, but I would phrase it slightly differently. Since we can't know the name of the project, for a given header `include/foo/bar/baz.hpp`, if there are multiple files `baz.cpp`, prefer the one with the longest common parent directory path. So prefer `src/alpha/baz.cpp` to nothing, prefer `src/beta/bar/baz.cpp` to `src/alpha/baz.cpp`, etc.

That way it can gracefully handle the situation where the include path doesn't have the project name as the top level directory (or other weird layouts).

> All of those proposed solutions are not only YCM specific, but Vim specific as well. Ycmd as a server is client agnostic. You can't expect ycmd-emacs to emulate vim features.

That's a good point, I hadn't considered other clients. Still, is there a way for the client to issue a command to the server that adds flags for a given file? Then this functionality could be implemented per editor.

**Comment by bstaletic** [comment]
> My only question would be the cost of finding the first file to include it.

That's my concern with it from the start. Imagine a template heavy codebase, something like ycmd's `cpp/ycm/ycm_core.cpp`, but every file is like that. Then you find `foo.h` and you start parsing file after file, just to check if one of them includes `foo.h`. Then you find `bar.h` and you start the parsing cycle again... That's not going to scale well.

I can already hear people say "let's cache the parsed translation units". Well, we already do that. There already is a `TranslationUnitRepository` class. It includes the flags with which the file was parsed and has hardcoded libclang options that were used for parsing. While the flags for parsing would be thte same, the libclang options won't be - we need diagnostics and all other things we can get in one case, but just the list of included files in the other. Maintaining two repositories would definitely consume too much RAM.

> is there a way for the client to issue a command to the server that adds flags for a given file?

No, because there's the extra conf that is much more flexible than any kind of semi-static list of flags. The compilation database support came because it's mostly a no-op, as it gets generated anyway.
Providing yet another way of providing flags in such a way doesn't seem beneficial enough, considering that `ycmd/completers/cpp/flags.py` is quite messy as it is now.

An alternative would be to fall back to having `clang++` as the only flag. While it could work, it can also silently fail and that's the argument for not providing any "default" - shout at the user that his flags are missing!

***

There's been quite a few ideas floating around. Personally, I'm starting to lose track, so, for my sanity, let's recap.

### Methods for figuring flags out

#### "Sibling" file in the same directory

- Already done, should be the most accurate, but isn't always available.
- Doesn't work for split source and header directories.

#### "Sibling" file in `src` instead of `include`

- Covers the case that isn't covered above.
- There's a question of whether `include/foo` directory tree mirrors `src` tree.

#### Any source file in the same directory as the header file

- Another case not covered above. (`s/include/src` finds nothing and there's no sibling file in the same directory).
- Not expensive to implement, but could potentially be wrong.
  - Example where this may fail is `gperftools` which has exactly *one* C source file and a bunch of C++. This could be treated as a corner case.

#### Parsing the source files in search for the right include statement

- Should be the most accurate way to find flags for the header in question.
- This is what `cquery` does, but it can be really expensive in a lot of ways. (I'm not a fan.)

#### "Sane" defaults

- If all else fails... hope `clang++ foo.cpp` is enough? 
- It may work for trivial projects, but will hide many many errors. I think it's better to yell at the user to provide correct flags.

#### Project hierarchies

#### Source and headers lumped together

- The current `master` works for those, unless there's a header that doesn't have a sibling file, in which case "any source from the same directory" will work.
- I'm not sure it's more common than the following type.

#### Source files separated from headers

- `s@include@src/foo@` will probably work.
- On the other hand, `foo` might not be part of the path and we need `s/include/src/`.
- Some other configuration would require checking the longest common parent path - it adds some complexity to `flags.py` mess.

#### Header only

- All bets are off. We only get test sources and we definitely won't find sibling files... Possible tactics are parsing and looking for a specific include statement or "a sane default". Both of which I'm against.

***

### Final thoughts (for now)

- The current solution should still have the top priority. It's fast, should be really accurate and there's an argument for backwards compatibility.
- Doing something like `s/include/src` sounds like a good idea. Let's just not get lost in trying to work out some obscure corner cases.
- Parsing sources for include statements is too expensive in my opinion. Note that i have not run any benchmarks.
- Sane defaults don't seem like a good idea to me. I know cquery guys would disagree.

**Comment by puremourning** [comment]
The only one i implemented in my "default extra conf" branch (which was the genesis of the compile commands support in ycmd) was some simple path manipulations which works for projects which (heinously!) put includes in different folder.

I would consider merging that but anything else is just guessing.

Anything that is more complex than the very simple heuristics we have requires a .ycm_extra_conf.py. I think that's a totally reasonable position, given that there is literally no change of us being right, or even close to right, in the general case.

**Comment by bstaletic** [comment]
You've got a point. I'm fine with requiring users to write their extra confs for strange project layouts. So let's figure out what's the best way to go from `include/proj/foo.h` to `src/foo.h`.

**Comment by puremourning** [comment]
this is what i do: https://github.com/puremourning/ycmd-1/blob/master/ycmd/default_ycm_extra_conf.py#L217

it basically works for the clang source _shrug_

**Comment by bstaletic** [comment]
What about projects where headers are in `include/<project>` and sources are in `src`? I'd add that to the list and call it a day.

**Comment by sam-lunt** [comment]
> What about projects where headers are in include/<project> and sources are in src? I'd add that to the list and call it a day.

In that case, I think it's important to get the order correct. Given the file `include/foo/bar/baz.hpp`, we might want to look for a source file either `src/bar/baz.cpp` or `src/foo/bar/baz.cpp`, since we can't know if `foo` is the project name or just a regular directory. However, if `src/foo/bar/baz.cpp` exists, we can safely conclude that `foo` is a regular directory (i.e. not the project name), and we should prefer `src/foo/bar/baz.cpp` to `src/bar/baz.cpp`

**Comment by bstaletic** [comment]
There was a post on /r/cpp that asked how people organizer their projects. Most of people there said they separate headers and sources.

**Comment by sam-lunt** [comment]
I think separate directories for `src` and `include` is fairly common. It makes installing headers much easier if using make, and even with CMake `install(DIRECTORY dirs... FILES_MATCHING pattern)`, there could be internal headers that don't merit installation.

I would suggest the following logic to determine the flags for a header file `foo.hpp` (ignoring other extensions for brevity):

1. If `$(pwd)/foo.cpp` exists in the compilation database, use that
2. If `$(pwd)/*.cpp` is non-empty, use that
3. If `$(pwd | sed 's/include/src/')/foo.cpp` exists, use that
4. If `$(pwd | sed 's@include/[^/]\+@src@)/foo.cpp` exists, use that

I think this would cover the three most popular (and reasonable) schemes for organizing C and C++ code. I feel like looking for a match to `$(pwd | sed 's/include/src')/*.cpp` might lead to too many false positives, but those could be added as options 5 and 6.

**Comment by puremourning** [comment]
> most popular (and reasonable)

I don't think we're in the business of determining what's reasonable. In the absence of evidence suggesting that a _significant_ number of projects affecting our users structure their projects this way, I would be against adding such heuristics and complexity. It's a slippery slope to "my project is structured like ***this***, can you edit ycmd code to support it?"... "No, use an extra conf file" ... "but you added _this_ heuristic!".

NOTE: i have been writing c/c++ for 2 decades and have never used that project structure. That doesn't mean that it's not popular, nor that it is unreasonable, but it also implies that "reasonableness" is subjective.

**Comment by micbou** [comment]
With PR https://github.com/Valloric/ycmd/pull/1215 merged, we now use the heuristic from Clang to find the flags in the compilation database, which [implements (among other things) the requested feature](https://github.com/llvm/llvm-project/blob/ea9773ac69389c6eac82384b3cf98ceb774ff740/clang/lib/Tooling/InterpolatingCompilationDatabase.cpp). Closing.
