### ISSUE TITLE
Introduction of Clangd Completer

### ISSUE THREAD

**Issue by kadircet** [Valloric/ycmd#1114]
## Hi everyone!
We’ve been implementing a new language server called [clangd](https://clang.llvm.org/extra/clangd.html) that implements LSP and have been using it in our internal system with YCM through a new completer for a while now instead of libclang. We wanted to upstream that completer so that other people can use it with YCM as well.  

### Need your opinions:
clangd comes as an external binary, our completer plugin looks for a clangd binary in the path and uses it as the LSP server. Also the binary has been shipped with clang-tools packages and LLVM releases. So they can be downloaded in numerous ways:
- [Debian packages](https://packages.debian.org/buster/clang-tools) (also [ubuntu](https://packages.ubuntu.com/cosmic/clang-tools) has it in its own repos)
- [LLVM releases ](http://releases.llvm.org/download.html) in the forms of [source code](http://releases.llvm.org/7.0.0/clang-tools-extra-7.0.0.src.tar.xz) and pre-built, [ubuntu](http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz), [windows](http://releases.llvm.org/7.0.0/LLVM-7.0.0-win64.exe), [macOS](http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz) binaries.
- Also available in [homebrew/llvm](https://formulae.brew.sh/formula/llvm).
- Also it is whitelisted in [Travis CI apt sources](https://github.com/travis-ci/apt-source-safelist/blob/master/ubuntu.json#L275).

So, we are wondering on how to make it available for ycmd CI pipelines in all environments in the most maintainable way possible:
- Would you suggest a similar way that has been used for libclang? IIUC, it downloads a precompiled library during tests, we can do the same with clangd download a pre-built version from llvm-releases.
- We can fetch the source code(again from llvm release) and build clangd on each environment.
- Or anything else that can be achieved with the above mentioned packages/releases.

**Comment by bstaletic** [comment]
First of all, I'm excited about moving ycmd from built-in libclang completer to something like clangd. We (ycmd maintainers) have been looking into things like clangd/cquery for a while. And we've had a couple of concerns, but generally speaking would like to switch because that would mean we could drop a lot of complexity. I'll get back to these later.

- Fetching sources and compiling clangd is too time and RAM consuming to be feasible as for CI so for some users, making the approach simply out of the question.
- Something like what we do for libclang seems like the best approach except:
  - What about users of OS's that don't have prebuilt binaries? Right now they can point to a custom libclang with `-DPATH_TO_LLVM_ROOT` or to the system libclang with `-DUSE_SYSTEM_LIBCLANG=ON`.
  - We have been told that we shouldn't download binaries from llvm releases directly on CI and so we ended up [repackaging only the necessary parts of the clang+llvm archives and uploading to bintray](https://github.com/Valloric/ycmd/blob/master/update_clang.py).
  - We have also had numerous reports from users whose distro doesn't come with `libtinfo.so.5`, but `libtinfo.so.6` and, since libclang links against libtinfo linux users had troubles. To the point where @micbou created https://github.com/micbou/llvm to host libclang for linux with minimal dependencies.
- There is an option of searching `$PATH` for `clangd`, but then we lose the guarantee that the users (at least most of them) are running the same version that we are testing.

Here's what our concerns are about any C++ server:
- Language support.
  - We currently are able to complete C, C++, Objective-C and as of recently CUDA. I'm guessing this is a non-issue, but a confirmation would be nice.
- Flags:
  - Does clangd support the CL driver? Once again, I'm guessing this isn't an issue.
  - Extra conf support. Using `.ycm_extra_conf.py` can be much more flexible than the compilation database and we want to keep that option. The ideal option would be for clangd to ask us for flags whenever it needs to parse a file. As far as we know that's not possible. What kind of works is what @puremourning did when he tried clangd out - [sending flags on didOpen](https://github.com/puremourning/ycmd-1/commit/69b41bde32e109f39bdccbd8d3d35ed9b36ed45a), but that mean that a file could be parsed once with wrong flags. Any better suggestions here? Considering "eventual consistency" this may not be too bad.
- Side question: What's the status of clangd when it comes to indexing the project and things like `GoToReferences`? As far as I know this is still WIP.

**Comment by kadircet** [comment]
>   * What about users of OS's that don't have prebuilt binaries? Right now they can point to a custom libclang with `-DPATH_TO_LLVM_ROOT` or to the system libclang with `-DUSE_SYSTEM_LIBCLANG=ON`.

It will be almost same, only they won't need to tell anything to ycmd. Because plugin will first search for a clangd binary in the path and go with that one instead of downloading. This might become only a problem for CI environments, but AFAIK above mentioned pre-built binaries cover all the CI environments used by ycmd.

>   * We have been told that we shouldn't download binaries from llvm releases directly on CI and so we ended up [repackaging only the necessary parts of the clang+llvm archives and uploading to bintray](https://github.com/Valloric/ycmd/blob/master/update_clang.py).

I would like to go with that way again if possible. clangd binary is linked statically(on clang and llvm side, not for libstdc++) as far as I checked on linux. We hope it is the same for windows and mac also(unfortunately cannot check at the moment). So it should be enough to extract clangd binary only end put it into bintray to be fetched by CI.

>   * We have also had numerous reports from users whose distro doesn't come with `libtinfo.so.5`, but `libtinfo.so.6` and, since libclang links against libtinfo linux users had troubles. To the point where @micbou created https://github.com/micbou/llvm to host libclang for linux with minimal dependencies.

As mentioned above, hopefully moving to clangd should resolve that problem. Current libraries that are needed by clangd on ubuntu16.04 release is:
```shell
$ ldd clangd 
	linux-vdso.so.1 (0x00007ffed27d8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f13be642000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f13be43a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f13be236000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f13bdf32000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f13bdbad000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f13bd995000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f13bd5f6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f13be85f000)
```

> * There is an option of searching `$PATH` for `clangd`, but then we lose the guarantee that the users (at least most of them) are running the same version that we are testing.

I believe this issue also exists for libclang. But hopefully this shouldn't be a big problem for clangd, because clangd is only an LSP server which speaks that protocol with ycmd, so version mismatches between server and client shouldn't be a problem as long as there is a backward-incompatible change in protocol itself. LSP has lots of capability features and it protects those problems from occurring as long as implemented correctly.

>   * We currently are able to complete C, C++, Objective-C and as of recently CUDA. I'm guessing this is a non-issue, but a confirmation would be nice.

Yes actually I adopted almost every test that libclang was looking, we are able to satisfy all of these languages according to tests.

>   * Does clangd support the CL driver? Once again, I'm guessing this isn't an issue.

Yes, this is again something done in clang level. Clangd is merely a proxy for compile commands.

>   * Extra conf support. Using `.ycm_extra_conf.py` can be much more flexible than the compilation database and we want to keep that option. The ideal option would be for clangd to ask us for flags whenever it needs to parse a file. As far as we know that's not possible. What kind of works is what @puremourning did when he tried clangd out - [sending flags on didOpen](https://github.com/puremourning/ycmd-1/commit/69b41bde32e109f39bdccbd8d3d35ed9b36ed45a), but that mean that a file could be parsed once with wrong flags. Any better suggestions here? Considering "eventual consistency" this may not be too bad.

That's something on our agenda as well, we are aware that it is important for people working on projects without compilation databases and even for people working with it, json compilation database is too concrete. Currently clangd doesn't respect extra_conf or per request flags, it always looks for a compilation database either json or a fixed one(compile_flags.txt). But we didn't want this to be a blocker for the patch. So we are actually going to make clangd_completer opt-in, so that people can try it out and we can see other complaints as well.  
Also we believe that the compilation database interface should rather be clangd specific, because hopefully clangd will not be used by only ycmd. That way every different editor plugin(extension) can have its own way of configuring compile flags.

> * Side question: What's the status of clangd when it comes to indexing the project and things like `GoToReferences`? As far as I know this is still WIP.

We actually have [index support](https://github.com/llvm-mirror/clang-tools-extra/blob/master/clangd/tool/ClangdMain.cpp#L161) within clangd and [clangd-indexer](https://github.com/llvm-mirror/clang-tools-extra/tree/master/clangd/indexer) that you can use to extract symbols from headers in a project to be used by clangd for codecompletion(or gotodefinition) later on. Unfortunately GoToReferences doesn't exist yet. Also this symbol support is biased toward only c++, it might not perform as good as it on obj-c or cuda.


---
Lastly, to move forward with the changes I am preparing, it would be really great if you(plural) can state your opinions about using bintray strategy. If everyone agrees I can send out a patch that will also upload clangd to bintray.

**Comment by bstaletic** [comment]
Falling back to looking for `clangd` in `$PATH` for cases where a precompiled archive doesn't eist sounds good. Using bintray sounds good as well, I'm sure others will agree. That `ldd` output looks sweet too!

As far as indexing goes, I believe that we don't need to have indexing in place without `GoToReferences`.

>  Currently clangd doesn't respect extra_conf or per request flags, it always looks for a compilation database either json or a fixed one(compile_flags.txt).

Are you saying that updating flags on `didOpen` message doesn't work? I remember @puremourning not only implementing the patch I linked above, but also claiming that clangd got the new flags.

> So we are actually going to make clangd_completer opt-in

We were never keen on supporting two completers for the same language. Is that what you are proposing here? The reason for avoiding multiple completers for a single language is maintenance burden. On the other hand, we have already mad a precedence with javascript and Tern/TSServer.

**Comment by kadircet** [comment]
> Are you saying that updating flags on `didOpen` message doesn't work? I remember @puremourning not only implementing the patch I linked above, but also claiming that clangd got the new flags.

Currently, we have an extension to LSP for handling extraFlags on didOpen requests. You can send flags but these are just "extraFlags". They do not overwrite what is in compilation database. They will only get appended, well if there is no compilation database then they will be the only compile commands.

> We were never keen on supporting two completers for the same language. Is that what you are proposing here? The reason for avoiding multiple completers for a single language is maintenance burden. On the other hand, we have already mad a precedence with javascript and Tern/TSServer.

Our plan is for clangd to eventually replace libclang-based completion (in all editors). We're not at full feature parity yet, but getting close. We think it's useful to have the editor integration available before switching the default, so early adopters can shake out problems and because the editor integration itself requires iteration.

Internally at Google, we're running a fork of ycmd and switched the default to clangd 6 weeks ago. We'd like to have some plugin support for major editors in time for the LLVM8 release (~5 months).

ycm_extra_conf: these use cases are important; it's also a tricky design space. We would like looser coupling between ycmd/clangd than between ycmd/libclang, and to share the mechanism with other tools and editors.

Concretely this might mean a slightly different format, and being invoked by clangd rather than YCM, but we still need to understand requirements and propose a design here.

Given that more feature parity and in particular ycm_extra_conf are going to take time, we would rather have it sent out without that support as an opt-in completer to be used with some compilation database. We would add that support in the meantime while people are also sending their opinions about the other missing features.

**Comment by bstaletic** [comment]
I believe all maintainers will agree that extra conf compatibility is needed if we want to switch to clangd by default. That said, I know quite a few users rely on compilation databases and don't use extra confs.

Here are a few more questions:
- Can we expect that, eventually, clangd will be able to correctly sanitize flags and not just those that could be read from a compilation database? More specifically, a user, in his extra conf, can have multiple positional arguments, just like on the command line (`clang++ foo.cpp bar.cpp`), but sending flags like that results in AST deserialization error. 
- Is include path completion also planned? Right now ycmd does that without using libclang.
- If I'm not mistaken, clangd doesn't expose an equivalent of `:YcmCompleter GetParent`, which actually calls `clang_getCursorSemanticParent`. Am I right to assume that one is on a TODO list, just with a low priority?

***

Regarding supporting two engines for C++, I can't make that call alone. I'm leaning towards allowing it, but I am very interested in what others have to say. I know it's not polite to ask for ETAs in open source communities, but can we have any idea how far clangd is from being at feature level needed to be used instead of the current libclang completer?

**Comment by kadircet** [comment]
> * Can we expect that, eventually, clangd will be able to correctly sanitize flags and not just those that could be read from a compilation database? More specifically, a user, in his extra conf, can have multiple positional arguments, just like on the command line (`clang++ foo.cpp bar.cpp`), but sending flags like that results in AST deserialization error.
> * Is include path completion also planned? Right now ycmd does that without using libclang.

Clangd already has support for completing include statements(added in last weeks).

> * If I'm not mistaken, clangd doesn't expose an equivalent of `:YcmCompleter GetParent`, which actually calls `clang_getCursorSemanticParent`. Am I right to assume that one is on a TODO list, just with a low priority?

Yes, GetParent and GetDoc are two missing subcommands(with some of the existing ones behaving different than libclang, due to the nature of LSP) that we plan to have support soon.

> Regarding supporting two engines for C++, I can't make that call alone. I'm leaning towards allowing it, but I am very interested in what others have to say. I know it's not polite to ask for ETAs in open source communities, but can we have any idea how far clangd is from being at feature level needed to be used instead of the current libclang completer?

It depends on what do you mean by "needed feature level", as mentioned currently it is being used inside Google with vim(and various other editors, it was also being used before LLVM7 release) and also externally there are various editors with their own clangd integration. But we plan to have big improvements before LLVM8 release as mentioned in previous post, which will happen in ~5 months.

**Comment by bstaletic** [comment]
> Clangd already has support for completing include statements(added in last weeks).

That's great news. I'm looking forward to testing that.

> GetDoc

Shouldn't that be a part of hover response? Clangd's documentation says hover request is supported.

> with some of the existing ones behaving different than libclang, due to the nature of LSP

Yeah, the LSP protocol can be a real "joy" sometimes.

> It depends on what do you mean by "needed feature level"

Fair enough. I'm starting to annoy myself a little, but primarily I was thinking of some sort of extra conf compatibility.

Thanks for all the answers.

**Comment by kadircet** [comment]
> > GetDoc
> 
> Shouldn't that be a part of hover response? Clangd's documentation says hover request is supported.

Unfortunately, our current Hover implementation doesn't fetch Comments, therefore it is not contained within hover response.
 
> Thanks for all the answers.

Thanks for the interest!

**Comment by micbou** [comment]
> Lastly, to move forward with the changes I am preparing, it would be really great if you(plural) can state your opinions about using bintray strategy. If everyone agrees I can send out a patch that will also upload clangd to bintray.

I am fine with the Bintray approach and I can take care of uploading the clangd binaries to my Bintray account if needed.

**Comment by kadircet** [comment]
Hey everyone, sent out #1117 and #1118 looking for your comments.

**Comment by micbou** [comment]
The Clangd completer is now part of ycmd. Closing.
