### ISSUE TITLE
Way to add custom semantic completer

### ISSUE THREAD

**Issue by mkusher** [Valloric/ycmd#127]
I'm working on [php completer](https://github.com/mkusher/padawan.php) and I've created simple [YCMD semantic completer](https://gist.github.com/mkusher/43bcff85d5e2f3ec3c55), but I failed in adding completer without modifying YCMD sources.
Is there a way to do it via additional configuration?

**Comment by vheon** [comment]
You cannot add a new semantic completer simply through configuration. What you should do is:

- Add your `padawan.php` as a submodule in the `third_party` directory.
- Add your `padawan_completer` as a semantic completer for ycmd, so after your changes the `ycmd/completers` tree should look like:

```
...
└── php
    ├── __init__.py
    ├── hook.py
    └── padawan_completer.py
...
```

- Add an End To End test to check in an automated way that your completer is integrated well in ycmd.

But, before you do all that you should look into #120. That PR is made for integrating CodeIntel (which is the semantic engine behind the Komodo IDE, if I'm not wrong) and should bring support for php. How that compares to your semantic engine?

**Comment by mkusher** [comment]
@vheon it's too bad :(

I've already made such structure in my local fork, using class I mentioned in previous post, but I don't like idea of adding it to the ycmd, because it needs additional configuration(path to composer command for example). 
Talking about CodeIntel I don't know what is the difference, because latest master from jeteon's repo doesn't work. 
My engine is written in php and works as http server, so that's the only difference I can find now.

**Comment by vheon** [comment]
>  because it needs additional configuration(path to composer command for example). 

It wouldn't be the first semantic engine that need extra information to work: 

- The clang completer require a `.ycm_extra_conf.py` for the flags to pass to clang.
- The Omnisharp server require a solution file at the moment.

> Talking about CodeIntel I don't know what is the difference, because latest master from jeteon's repo doesn't work. 

That is unfortunate, I was curious :+1: 

A question: from what I understood, you completer require that the php project for which I want completions has to use the composer tool, am I right?

**Comment by mkusher** [comment]
Yeah, as of now it only can work with classes and interfaces that could be dumped with `composer dumpautoload -o` command. I am trying to get out of it, but it needs some extra work.
Don't you think that plugin-way of adding semantic engines is more flexible? User can decide what engine he want to use and even write condition, for example in vimrc, when to use one or another.

**Comment by vheon** [comment]
> Don't you think that plugin-way of adding semantic engines is more flexible? User can decide what engine he want to use and even write condition, for example in vimrc, when to use one or another.

I did the same question https://github.com/Valloric/ycmd/issues/84#issuecomment-73140815 and in the end I agree with @Valloric that would be work for little gain. I would prefer spend time improving a completer instead of searching for alternative for a single use case and switching just for that use case.

> for example in vimrc

You have to remember that ycmd is editor agnostic :stuck_out_tongue:

**Comment by mkusher** [comment]
>You have to remember that ycmd is editor agnostic 

I do, that's why I wrote "for example" ;)
Since my project depends on composer autoloader, I'm not sure, that it is good for all php cases and should go in ycmd as semantic engine for php. These is not really good for users who wants to use my completer, because there would be extra steps in install process. And you have already two PR(CodeIntel and Hack completer) that would do something similar. Have no ideas what to do.

**Comment by cweagans** [comment]
The Codeintel completer is the code intelligence engine from Komodo Edit, and does more than just PHP. It also has the advantage of working with old PHP4-style projects and PHP5 projects that don't use Composer.

Hack is a separate thing, so I wouldn't worry about that. The Hack completer won't have any relation to PHP at all.

**Comment by mkusher** [comment]
That's exactly I'm talking about. In general case CodeIntel should be useful and it make sense to include it in ycmd, but then how one would use padawan.php?
 "having a choice" is a really good thing.

**Comment by vheon** [comment]
> In general case CodeIntel should be useful and it makes sense to include it in ycmd

So are you saying that there are situation where CodeIntel would not be a good choice for php?

**Comment by cweagans** [comment]
Personally, I think Codeintel is a more complete, performant completer than anything that can be written in PHP, and it's being improved by a company that has a commercial interest in making it better (Activestate). While I like the idea of having PHP-related tools written in PHP so that users of the tool can improve it, the performance just isn't there and a 1-2 developer team won't be able to keep up with Activestate's codeintel team.

All of that said, it would be really cool to be able to plug in external completers without having to have them in the ycmd codebase so that if somebody *wants* to use padawan instead of codeintel, they can.

**Comment by vheon** [comment]
> Personally, I think Codeintel is a more complete, performant completer than anything that can be written in PHP, and it's being improved by a company that has a commercial interest in making it better (Activestate). While I like the idea of having PHP-related tools written in PHP so that users of the tool can improve it, the performance just isn't there and a 1-2 developer team won't be able to keep up with Activestate's codeintel team.

I absolutely agree with this. As much as I love to hack on this kind of things, my spare time is not comparable with people doing this full time.

> All of that said, it would be really cool to be able to plug in external completers without having to have them in the ycmd codebase so that if somebody wants to use padawan instead of codeintel, they can.

The work needed in making this layer configurable, plus the work needed for maintaining it and the time IMHO are not worth it. Not to mention the time needed when people will come here because somethings is broken and you have to replicate the condition using whatever they are using as a semantic engine. I'm for a sane default that works instead of fully configurability.

I don't understand why one would want to work with a completer X that does not provide the same quality of completion of a completer Y. @mkusher This is not a thing directed to you, but It's a general thought of mine. If your padawan.php turns out to be better than CodeIntel I think that would be natural to replace CodeIntel with it.

**Comment by mkusher** [comment]
I've tried OpenKomodo yesterday, it has good completion for php. I can't say that my padawan.php is already complete solution for php, but there are some situations when my padawan.php shows completion and OpenKomodo don't. Of course there are also many situations when OpenKomodo shows completion and my padawan.php don't. And that is what I'm talking about. Completer A can complete A and completer B can complete B. A is useful for one group of people and B for other group. And only one group of people able to use YCM.
I don't say we need to include padawan.php into the ycmd, CodeIntel looks faster and more stable, but I want to find a way for easy integration with YCMD for padawan.php users.

**Comment by Valloric** [comment]
There is no support for user-level Completer implementations. It's an internal-only API.
