### ISSUE TITLE
Is there supposed to be one ycmd per vim?

### ISSUE THREAD

**Issue by unphased** [Valloric/ycmd#128]
I was wondering if maybe we could make better use of system resources if ycmd could be a "shared resource" when multiple vims are running. 

I did some playing around with new terminal emulators from my iOS devices recently, and when the connection abruptly dies this seems to cause some SIGHUPs to not be sent around properly (probably SSH's fault) and that was causing vims I started under an SSH shell to not properly exit. They each would then host their own ycmd, which seem to consume between 250MB and 600MB of RAM each. 

While I do intend to continue to use tmux at all times, and this has multiple benefits including cutting down on the vim instances, I still wonder if this could be improved.

**Comment by Valloric** [comment]
> I was wondering if maybe we could make better use of system resources if ycmd could be a "shared resource" when multiple vims are running.

The intended configuration is one ycmd per editor instance. Other configurations are unsupported. There are complicated reasons for this that involve supporting the loading of separate libclang binaries into ycmd per editor instance. It also simplifies other parts of ycmd if it can assume only one client.

> that was causing vims I started under an SSH shell to not properly exit. 

Seems like the root of your issue is that your vim instances are sticking around. A disconnected ycmd will shut itself down after a while.
