### ISSUE TITLE
Why GPL3 for YouCompleteMe and ycmd?

### ISSUE THREAD

**Issue by tony** [Valloric/ycmd#139]
https://github.com/Valloric/ycmd/issues/21 This discussion here was closed, along with others:

- https://github.com/Valloric/ycmd/issues/20
- https://github.com/Valloric/YouCompleteMe/issues/363

I have a few clarifications directed toward the author, @Valloric . When these is issues are being closed, it gives me the impression these issues seem cut off with little sensitivity to the ramifications for users downstream.

1. Why did you choose to viral license ycm and youcompleteme? 

2. Are you aware that one of the primary reasons behind LLVM / Clang's stakeholder's incubating it was to avoid viral licensing, namely, GPLv3 in gcc/gdb?

3. Are you aware of the ramifications of how permissively licensed projects and their users have to go out of their way to reinvent the wheel so as to not risk cross-contamination with GPL?

**Comment by oblitum** [comment]
IMO, I think it's good to have this stated short and simple for reference without much further discussion. Personally, I think there's no big issue regarding cross-contamination with a client/server model since new clients, even with permissive licenses, can request their users to download the server or link to it as a submodule. And I think the client being GPL does more good than harm. This project is not part of LLVM and libclang completion is just one of the several completers.

**Comment by Valloric** [comment]
I closed and locked those issues (as I will close and lock this one) because discussing something that can't be changed is pointless and a waste of everyone's time. Would I have picked Apache v2 instead of GPL v3 if I were doing this again? Most likely. But that doesn't change the fact that YCM will remain GPL v3; we can't change it now for so many reasons.

Please don't start new issues about this.
