### ISSUE TITLE
python - no completions for keywords, import statements 

### ISSUE THREAD

**Issue by DGalt** [Valloric/ycmd#169]
I am testing this in Emacs using emacs-ycmd. The examples below have been compared to the completions I get with Anaconda-mode (abbrev: AM), which is another python completion package for Emacs that also uses Jedi. 

In a blank / fresh python file, the behavior I'm seeing is: 

**No completions for Python keywords**
Examples: 
`imp` does not provide any completion suggestions, whereas with AM I get:
```
import
ImportError
ImportWarning
```

`exc` does not provide any completion suggestions, whereas with AM I get: 
```
except
Exception
```

`pri` does not provide any suggestion, whereas with AM I get `print` 

Once a keyword has been used once, it comes up for autocompletion, but I still fail to get any other completions that may match that string. For example, if I use `import` once when I type `imp` I will now get a completion suggestion of `import` but I still fail to get the other keywords that potentially match that string

**No completions for import statements**
Examples: 
`import da` provides no suggestion, whereas AM gives me `datetime`

`from glob import gl` provides no suggestions, whereas AM gives me: 
```
glob
glob0
glob1
```

similarly: `from sys import pa` provides no suggestions, whereas AM gives me: 
```
path
path_hooks
path_importer_cache
```

Once imported, though, completions for the module work fine. So, for example:
```
import glob
glob.g
```

gives the expected completions for `glob.g`

I've also tested this with third-party packages (matplotlib, PyQt4) and see similar behavior. 

@abingham  in case this turns out to be emacs-ycmd specific

**Comment by Valloric** [comment]
Thanks for the detailed test case; I finally understand the issue, and this is actually Working As Intended™. 

The root of the matter is that ycmd and anaconda have a different completion philosophy. With ycmd, there are two separate completion "modes": the identifier-completion that's used when the user is typing most words and the semantic completion which triggers after the user enters a "semantic trigger" in the buffer.

So for python, the semantic trigger is ".", so when you enter that (or it's a few chars before your cursor), ycmd queries the Jedi semantic engine for completions. In all other situations, ycmd uses the identifier completion engine which is non-semantic and merely matches what you typed against the identifiers in your current file and other files of the same type you have opened and visited.

So if you had

```
import
ImportError
ImportWarning
```

somewhere in your file and you started typing `imp`, you would get those completions because the identifier engine would see them. Otherwise, no.

YCM (and probably emacs-ycmd too, though I'm unsure), the Vim client for ycmd, supports forcing a semantic engine query with `<ctrl-space>`.

The reason why things work this is way is because semantic engines tend to be slow and querying them for every keystroke in the file wouldn't be a good user experience. Most of the time, the "dumb" identifier engine provides good-enough results.

**Comment by DGalt** [comment]
Thanks for the clarification, that makes a lot of sense. Looking through the emacs-ycmd command list there is one to toggle forced semantic completion on/off. With it on I more or less get the behavior I observe with Anaconda.
