### ISSUE TITLE
Feature request: pluggable general completers

### ISSUE THREAD

**Issue by wladston** [Valloric/ycmd#192]
Creating a new issue not to mix with other things mentioned in issue #190.

It would be a great idea to let other people write plugins that extend Ycmd's functionality, in the same way one can write a pluggable snippet module to a snippet engine. One example of this idea is vim-snippets, a pluggable module that provides snippets to the  Utilsnips engine).

That could be accomplished very easily by loading external python modules in the GeneralCompleterStore class. The external modules can be loaded by scanning directories defined in a special Ycmd-defined environment variable, for instance.

This would allow anyone to write completers without express approval from Ycmd's commit team functioning on Ycmd. This would immensely lower the entry barrier for new completion opportunities, without creating any additional complexity for those who only want to use Ycmd without any pluggable components.

It would also potentially simplify Ycmd's codebase, as the Utilsnips completer, for instance, could be moved into a separate, pluggable module for those who want to use Utilsnips.

**Comment by Valloric** [comment]
This was once a design goal, but stopped being one. The rationale is as follows: if we make it possible to plug in new completers externally (without them being in the ycmd codebase), we have two problems:

1. The internal Completer API now needs to become a stable public interface. We can't just change it willy nilly because we'd break all the external completers. This isn't something I'm willing to commit to, since it would greatly impact our ability to evolve the internal ycmd completers.

2. Much worse than the previous issue, if we make it possible to load new completers without upstreaming them, nobody would ever upstream a completer! Why deal with the hassle of writing code that's good enough to pass merge review, write tests for the code and update the completer when new ycmd features require it (all of which happens when the completer is in ycmd) when you can just plop your code in a random place and tell people to use it. There's no pushback. When the completer is upstreamed into ycmd, everyone can just update it in one place as we change ycmd internals.

The second reason is the critical one. With the current setup, if someone wants to write a completer for language Foo, they need to upstream it. This is a Good Thing™ because everyone benefits from that; if at any point ycmd gets new features that we want the completers to support, we can just go in and change it all without breaking anyone.

**Comment by wladston** [comment]
@Valloric, thanks a lot for the detailed response. I deeply appreciate and respect your opinion. Since the completer I want to make won't be upstreamed (because of #190), the only way left for it to be distributed is as a monkey patch :monkey: :package: :stuck_out_tongue_winking_eye:

**Comment by vheon** [comment]
@Valloric I agree one hundred percent with your thought; my only concern with this approach is that we don't have a way to select which completer we want. Is a all or nothing thing and if it isn't a real problem at this exact moment could be in the future since the size of YCM and ycmd will grow linearly with the number of completers.  I would love that unless specified, ycmd would not download the semantic engine at all.
