### ISSUE TITLE
Unhandeled exception in 'event_notification' handler breaks completion

### ISSUE THREAD

**Issue by WilkGardariki** [Valloric/ycmd#289]
Hi.

I have a problem while using ycmd in emacs with C/C++ code without providing .ycm_extra_conf.py. It seems like ycmd breaks in some way and does not provide completions.

What do I do:
1. Open emacs.
2. Open some file with C++ code while there is no .ycm_extra_conf.py file anywhere around .cpp file.
3. Enable ycmd and company modes.
4. Type part of some word.

Then I get message "Ycmd completion unavailable while parsing is in progress." So ycmd did not update it's status to 'parsed' or something like this. However, if I ask ecmd to display completions it does. Also there is a traceback of exception from ycmd itself in server log.
![2015-12-27 00 55 12](https://cloud.githubusercontent.com/assets/877227/12071581/7929a9e8-b0c4-11e5-9f28-42f52e9c1ae2.png)

I've made some investigation in emacs modes sources and did not find any obvious problem there. So I decided to look at ycmd sources and especialy at the place from which exception was raised. This way I've found out that exception NoExtraConfDetected is not handled in any way. To workaround this I've added 'try...except' block in 'event_notification' handler. There I simply write a warning log message.

After all I've got exactly what I wanted: ycmd completions without usage of semantic clang completions.

I understand, that clang completions is kinda core feature here, but I think that user should be able to use ycmd for completions even without additional setting like .ycm_extra_conf.py file.

So my questions are:
1. Is the behaviour I've seen reproducible in other editors that use ycmd?
2. If the behaviour is reproducible, is it intended behaviour? Otherwise there is a problem on emacs side and I'll create issue for ycmd-mode.

**Comment by vheon** [comment]
I believe that this is a problem with the emacs client. Can you look at https://github.com/abingham/emacs-ycmd/issues/228#issuecomment-167386899 and see if is the same issue?

**Comment by puremourning** [comment]
@WilkGardariki if you don't want c++ semantic completion, then i would suggest not adding `--clang-completer` when building ycmd. This will build `ycmd` without the clang completer.

The best docs for the `build.py` script are actually the [Vim client's README.md](https://github.com/Valloric/YouCompleteMe/blob/master/README.md#installation)

**Comment by WilkGardariki** [comment]
@puremourning Heh, I want to be able to use semantic completions whenever I wat it. But when I don't want it, I'd like to use common completions. Moreover, ycmd has this nice fuzzy matching, that is missing in emacs company-mode)

**Comment by WilkGardariki** [comment]
@vheon, you may be right. I will go deeper in emacs-ycmd. I just thought that unhandled exception is kinda weird. The thing that confused me is that every thing works just fine after addition of exception handling.

**Comment by puremourning** [comment]
@WilkGardariki FYI the exception is converted to a http error response which is handled by the client, to inform the user that they are missing some setup. Without it, we get bug reports that simply say 'YCM not working' and we have to say 'RTFM' :)

The reason you're getting identifier-based completions is because of [this PR](https://github.com/Valloric/ycmd/pull/198), which adds fallback in the case where the semantic completer fails.

**Comment by Valloric** [comment]
@abingham You might be interested in this.

**Comment by WilkGardariki** [comment]
@puremourning thanks for explanation. Basicaly, it works, cause I've made some investigation before posting issue) I'll look deeper at error handeling in emacs-ycmd. Thus It would be great to transfer this issue there)

**Comment by puremourning** [comment]
So I think we can close this issue then. These exceptions are a (somewhat undocumented) normal part of the (somewhat undocumented) ycmd API. They are only raised once (see https://github.com/Valloric/ycmd/blob/master/ycmd/completers/cpp/flags.py#L81-L83), and identifier completion in Vim client works normally after ignoring the message:

![ycm-no-flags](https://cloud.githubusercontent.com/assets/10584846/12072014/6d481854-b0c3-11e5-9bb3-1dfe8892c442.gif)

I suppose at best we can say that we need to document the API, which is covered by https://github.com/Valloric/ycmd/issues/242.

I don't think we want to remove the message/warning for the reasons I mentioned before. They [were](https://github.com/Valloric/YouCompleteMe/issues/41) [added](https://github.com/Valloric/YouCompleteMe/issues/415) because there are manual configuration steps required to make the plugin work for C-family languages, and with the greatest will in the world, some folk just don't read the docs :grimacing:

**Comment by abingham** [comment]
@WilkGardariki We've [recently improved the exception handling in `emacs-ycmd`](https://github.com/abingham/emacs-ycmd/commit/ca77c334f9574bc42dd65869ff911b09f9e19c46). If you update to the most recent code do things work better?

**Comment by WilkGardariki** [comment]
@abingham Yep, just after this issue was closed, I began investigation in emacs-ycmd. Thus I've updated it and found out that everything is fine. Thanks)
