### ISSUE TITLE
Use the filetype to detect language when using compile_commands.json

### ISSUE THREAD

**Issue by hackaugusto** [Valloric/ycmd#337]
The check for [c++ or c](https://github.com/Valloric/ycmd/blob/255a1f4cadd9b214020c88629acbb2ea7154d8cf/ycmd/completers/cpp/flags.py#L229-L230) uses a [regex](https://github.com/Valloric/ycmd/blob/255a1f4cadd9b214020c88629acbb2ea7154d8cf/ycmd/completers/cpp/flags.py#L54-L58) that does not correctly identify the language, `cc` can compile a C++ file just fine. As a suggestion I think the `filetype` is a best indicator of the language and allows the user to fix detection erros.

Related [issue](https://github.com/rizsotto/Bear/issues/109) in the Bear project.
Related issue in ycmd #266

**Comment by micbou** [comment]
We cannot use the filetype because the compiled file is not necessarily opened in a editor. In addition, the filetype is almost always based on the file extension and using the file extension to pick between C or C++ is worse than using the compiler name. Think about header files: `.h` extension is used for both languages.

> cc can compile a C++ file just fine.

Not without the proper flags (try to compile a C++ hello world program with `clang` instead of `clang++`). This is also not the [recommended way](https://www.freebsd.org/doc/en/books/developers-handbook/tools-compiling.html):
> If you are compiling C++ code, use c++.
