### ISSUE TITLE
Strange caching behavior on completions requests

### ISSUE THREAD

**Issue by vincentwoo** [Valloric/ycmd#430]
Hi there,

In testing YCMD as a remote completion API, I appear to be hitting a weird caching bug. I'm just testing against Jedi autocompletion currently.

For the buffer

```python
import requests
import datetime

requests.
```

I (on the remote server where ycmd is running), write out the buffer to the filesystem, send a `FileReadyToParse` event to YCMD, and then ask for completions. This works okay, I get the appropriate results for `requests`.

However, If I change the buffer to:

```python
import requests
import datetime

datetime.
```

and perform the same actions, I still get returned the completion results for `requests` and not `datetime`. I believe this to be because of YCMD's caching on line and character offsets. Is there an API for saying "this buffer needs to be reparsed"? I couldn't find one in the sample client.

**Comment by vincentwoo** [comment]
On a bit of further digging I realized that YCMD provides [hooks](https://github.com/Valloric/ycmd/blob/30b04ebd1458d8a09e14587b57e81aabc15e2a53/ycmd/completers/completer.py#L253) for completion engines to listen to editor events. However, I could not find evidence that these had been overridden in the Jedi completer. This problem also seems to happen with JavaScript, even though the tern completer has an [OnFileReadyToParse](https://github.com/Valloric/ycmd/blob/30b04ebd1458d8a09e14587b57e81aabc15e2a53/ycmd/completers/javascript/tern_completer.py#L194) hook.

**Comment by vincentwoo** [comment]
Furthermore, the completer engine appears to to ignore `filepath` for caching purposes. This suggests that YCMD is built to only complete one buffer at a time. Is that correct, and if so, are there any ways to work around the issue?

**Comment by Valloric** [comment]
@vincentwoo Well ycmd is designed for editor completion on a local box with one user. Zero thought has been put into multi-user support since it's not a feature localhost editors need. There's probably plenty of issues in ycmd that would prevent multi-user support.

We might be willing to accept patches improving multi-user support, but only if they're _very_ low-maintenance.

The caching issue you've hit is indeed a corner case that can happen when two same-length names of the two different objects are used on the same line & column. It's pretty rare though, but we should fix it somehow.

You may want to read the comments (and the code) in `completer.py` to understand how the caching works.

**Comment by vincentwoo** [comment]
Cool, yeah it's not a huge deal to go multi-user, might be able to hack around it from the outside.

I think fixing the same line + column bug would be pretty rad though, but not entirely sure where it should be done. Should, say, `completer` cache based on file hash as well? Symbol name being completed?

**Comment by Valloric** [comment]
> Should, say, completer cache based on file hash as well? Symbol name being completed?

Whatever it is, we need to be careful about performance. This code is executed frequently.

Probably easiest would be filename (not full path) + the contents of the line up to the cursor.

**Comment by micbou** [comment]
I am not sure about the filename: it can be changed without changing its contents.

For the contents, it must be up to the column start or the cache will be invalidated while the user types characters to filter candidates.

**Comment by vincentwoo** [comment]
I lack a lot of python know-how. Is there any chance one of you two can address this issue? It'd probably benefit all YCM users.

**Comment by vincentwoo** [comment]
Having investigated this more thoroughly, I would actually like to advocate for **removing all caching behavior entirely**.

According to `completer.py`:

>   The cache is important and is a nice performance boost. When the user types in
  "foo.", your completer will return a list of all member functions and
  variables that can be accessed on the "foo" object. The Completer API caches
  this list. The user will then continue typing, let's say "foo.ba". On every
  keystroke after the dot, the Completer API will take the cache into account
  and will NOT re-query your completer but will in fact provide fuzzy-search on
  the candidate strings that were stored in the cache.

However, this appears to not actually be true in practice because the validity check keys on the *exact* column queried:

```python
def _CacheValidNoLock( self, current_line, start_column, completion_type ):
  return ( current_line == self._line and start_column == self._column and
           completion_type == self._completion_type )
```

I don't think the caching layer is actually saving any time for the case described. Additionally, I can't find any code doing fuzzy-search on top of the results returned by the cache.

As such, I think it would greatly simplify the design of the completer, improve latency by removing a lock in the critical path, and make YCMD more usable by other editors if this caching behavior was removed entirely.

If that's entirely unacceptable, I'd also advocate for either:

a) Making caching at least cache per-file. Right now the cache appears to be global per each completer.
b) Allow caching to be disabled conditionally view options.

**Comment by micbou** [comment]
See my PR #442 and in particular the tests. You'll have a better understanding of what and why we are caching.

**Comment by vincentwoo** [comment]
@micbou I think that PR still does not address fundamental issues with the caching strategy employed by YCMD.

#### Ycmd still shares the cache between all files

Accessing the same line, col in two different files that use the same completer will return whatever results came in for the first file in both cases, which is almost always wrong.

#### Keying based on start of line value is not enough

Keying the cache based on line value up to the cursor column still does not address very common behavior that should invalidate the cache. Take for instance, this code:

```c
Struct Foo {
    int x;
}
int main() {
    Foo foo;
    foo.
}
```

Completing at the dot will correctly return a completion of type "int". However, if you edit the struct to turn the int into an int array:

```c
Struct Foo {
    int x[10];
}
int main() {
    Foo foo;
    foo.
}
```

The completion at the same position will still be cached (because it's local to the line)

#### It's not clear why we need the cache

Given that initial completions *still* need to be fast enough, I believe that it should be on the editor to do follow-up fuzzy filtering on the initial results returned, not YCMD.

**Comment by puremourning** [comment]
Maybe we should keep the cache and invalidate it when a request is sent
with 'force_semantic' set to True.

This would solve your example, as the user can hit <ctrl-space> to get it
to force update.

**Comment by vincentwoo** [comment]
That's something I'd be happy with. I'll prep a little PR for it.

**Comment by micbou** [comment]
> Keying the cache based on line value up to the cursor column still does not address very common behavior that should invalidate the cache.

This never happens in practice because while the user modifies the file, subsequent requests will be sent to the server and [the cache will be invalidated](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/completer.py#L126).

If you think about it, we can't cache the completions in a perfect way: even the whole contents of the file would not be enough since other files may affect the completions in the current file. Is this a reason to not cache at all? No because the scenario where two subsequents completions requests are done with:
 - same completer;
 - identical line columns (or identical current lines up to start column);
 - identical start columns (start column is where the completion start, not the column number);
 - but different completions are expected;

is extremely unlikely in a file editing context.

> It's not clear why we need the cache

Because of this typical scenario: the user ask the server for semantic completions (for example by typing a `.` in some language), then once the user get the completions (which is costly), he continues to type characters to filter the results (which is almost free because of caching).

> Given that initial completions still need to be fast enough, I believe that it should be on the editor to do follow-up fuzzy filtering on the initial results returned, not YCMD.

So you are suggesting to remove the main feature of ycmd and that each client should implement it? What the point of ycmd then? And how is it better to do it client-side instead of server-side? Client is less aware than the server about the completions.

> Maybe we should keep the cache and invalidate it when a request is sent with 'force_semantic' set to True.

Probably better to add a parameter `cache` to the request that is `True` by default.

**Comment by vincentwoo** [comment]
> This never happens in practice because while the user modifies the file, subsequent requests will be sent to the server and the cache will be invalidated.

This is actually not true. In my C examples earlier, I literally submit each subsequent request with a different filename. Ycmd is not smart enough to invalidate the cache.

**Comment by vincentwoo** [comment]
> So you are suggesting to remove the main feature of ycmd and that each client should implement it? What the point of ycmd then? And how is it better to do it client-side instead of server-side? Client is less aware than the server about the completions.

I don't want to get into a protracted argument on this particular point,, but Ycmd's "fuzzy filtering" is in actually very strict. I'm doing filtering on the clientside and it is

1. way more responsive
2. way more configurable

That said, having a sane default for filtering makes a certain amount of sense, so I'm fairly happy with the earlier suggestion of just having a request parameter to disable caching per-request.

**Comment by Valloric** [comment]
I've discussed this issue with @micbou and @puremourning and we've come to the conclusion that this is a rare corner-case that doesn't really impact clients that ycmd is designed to support, namely localhost editors with one editor instance (used by one user) mapping to one ycmd instance. The user editing the buffer would invalidate the cache before `requests.` became `datetime.` so this would never occur. 

It can only arise in what ycmd would consider uncommon cases that the designed-for category of clients would rarely if ever produce. Solutions to fix this involve a loss of performance for _all_ cases or other corner-case problems, so fixes aren't free.

Since the current caching logic has been in place for 3+ years without much (if any, as I recall) complaints about this until now, it doesn't seem worth fixing.

Thanks for filing an issue though! We'll keep this in mind in case it rears its head in other circumstances.

**Comment by vincentwoo** [comment]
@Valloric Can you explain how the cache is invalidated? If I can do that over the official API, that's good enough for me, and I won't need the flag. My examination of the source code suggests this never happens though:

The only time `Invalidate` is invoked is here:

```python
  def ShouldUseNow( self, request_data ):
    if not self.ShouldUseNowInner( request_data ):
      self._completions_cache.Invalidate()
      return False
```

which calls

```python
  def ShouldUseNowInner( self, request_data ):
    if not self.prepared_triggers:
      return False
    current_line = request_data[ 'line_value' ]
    start_column = request_data[ 'start_column' ] - 1
    column_num = request_data[ 'column_num' ] - 1
    filetype = self._CurrentFiletype( request_data[ 'filetypes' ] )

    return self.prepared_triggers.MatchesForFiletype(
        current_line, start_column, column_num, filetype )
```

Whether `ShouldUseNowInner` returns true or false does not seem to be to be something that is modifiable via the JSON API (though the trigger code is admittedly complex).

The hooks I'd suspect of doing some invalidation appear to all pass by default as well:

```python
  def OnFileReadyToParse( self, request_data ):
    pass


  def OnBufferVisit( self, request_data ):
    pass


  def OnBufferUnload( self, request_data ):
    pass


  def OnInsertLeave( self, request_data ):
    pass
```

**Comment by Valloric** [comment]
If by "official API" you mean the Completer interface, note that that is _not_ part of ycmd's API to clients (as we state in the README). The _only_ client API we support is the REST interface. Everything else is ycmd internals that may change at the drop of a hat.

That being said, from my reading of the code, the only place we invalidate the cache is in the snippet of `ShouldUseNow` you cited. In other words, the cache is not exposed to subclasses. (As documented by the `_` prefix on `_completions_cache`, which means it's a private var.)

**Comment by vincentwoo** [comment]
Right, I didn't mean via Python, I meant from the REST API. I'd like to know how I can stagger my requests (similarly to however the officially supported clients do) such that they manage to invalidate the cache and not see stale results.

**Comment by micbou** [comment]
Sending a request with `line_num` set to `-1` should be enough. `ShouldUseNowInner` will return `False` in this case.

**Comment by vincentwoo** [comment]
Interesting. Does that happen in the official clients? Take my old example:

```c
Struct Foo {
    int x;
}
int main() {
    Foo foo;
    foo.
}
```

If a user in vim with YCMD goes back and changes "x" to "y" between completion requests at the dot, will the cache actually be invalidated in practice?

**Comment by micbou** [comment]
Yes because a request will be send when removing `x` and typing `y`.

**Comment by vincentwoo** [comment]
Oh, now I understand. I did not realize the behavior was to send a request for literally every keystroke. Okay, I'll simply maintain a fork that just snips out completions, which should be sufficient for my needs. Thanks for the explanation.

I do think it would be valuable to expose more power via the API but it is obviously at your discretion what to support in your project.

**Comment by micbou** [comment]
While I suppose it won't be enough for your use case, we have improved the caching behavior in PR #958. Cache is now invalidated in your example.
