### ISSUE TITLE
Java backend

### ISSUE THREAD

**Issue by rsolomakhin** [Valloric/ycmd#45]
Is there a plan to add support for Java in ycmd?

**Comment by vheon** [comment]
There's this project I've been watching https://github.com/jostillmanns/javacomplete. It uses [jdt.core](http://www.eclipse.org/jdt/core/index.php) and already have an api. I still haven't test it but is looks promising.

**Comment by Valloric** [comment]
Also possibly useful: https://github.com/javaparser/javaparser

I do think that jdt.core seems like the best bet though, but having options is good.

**Comment by vheon** [comment]
@Valloric javaparser cannot handle unfinished source file so is not suited for completions :( I was talking with @kamichidu about implementing a new parser for java in golang from scratch actually :smirk:

**Comment by Valloric** [comment]
For reference, here's the [JDT/Core source code on GitHub](https://github.com/eclipse/eclipse.jdt.core).

**Comment by wsdjeg** [comment]
now i am using https://github.com/artur-shaik/vim-javacomplete2
it works well for me

**Comment by Valloric** [comment]
The underlying semantic engine for vim-javacomplete2 is [javaparser](https://github.com/javaparser/javaparser) which admittedly looks pretty nice. We'll still probably go with jdt.core because that's used by Eclipse so it's used by millions and has a huge amount of features.

**Comment by vheon** [comment]
@Valloric actually is slightly different: vim-javacomplete2 use [javaparser](https://github.com/javaparser/javaparser) for files that are in a saved state and complete, since it can't handle unfinished code, and an internal java parser written in VimL for the file that we're currently writing which can handle unfinished code. I would go for the double parser approach but using jdt.core for the unfinished code and that is because using the AST API of jdt.core is pretty slow, in fact Eclipse don't use it all the time but have a system that gives you a high level view of the project and the objects but don't give you the errors like missing `;` etc etc.

**Comment by Valloric** [comment]
Huh. The rabbit hole goes deeper it seems. I assumed that jd.core would be fast and production-ready for completion + diagnostics since it's used by Eclipse.

**Comment by icholy** [comment]
Visual Studio Code just got Java support and it's using it's own wrapper around JDT.

* https://github.com/gorkem/vscode-java
* https://github.com/gorkem/java-language-server
* https://github.com/Microsoft/language-server-protocol

**Comment by Valloric** [comment]
@icholy That's pretty sweet, I'm all for using that java-language-server then if it ends up being fast. @vheon Mentioned in a previous comment that jdt.core might be too slow, but it's worth trying out.

**Comment by icholy** [comment]
Fast enough for vs-code fast enough or us, no?

**Comment by Valloric** [comment]
> Fast enough for vs-code fast enough or us, no?

I don't know what their standards for speed are, I only know what ours are (and they're pretty high). I don't expect this to be slow though if they're already using it.

**Comment by icholy** [comment]
I'll throw together a prototype when I have some time.

**Comment by vheon** [comment]
the thing that puzzles me here is that if you read https://github.com/gorkem/java-language-server#first-time-setup it looks like you have to basically install Eclipse 😕  But I would love to see it working 😜

**Comment by Valloric** [comment]
@vheon Oh that's ridiculous.

**Comment by puremourning** [comment]
Hah. Didn't eclim already solve this ?

**Comment by icholy** [comment]
@puremourning I've never had a good experience with eclim

**Comment by wsdjeg** [comment]
@icholy did you use javacomplete2?

**Comment by icholy** [comment]
@wsdjeg no, but I think support for this protocol goes beyond java. It gives us all the vs-code back ends for free. That's a no brainer for me.

**Comment by puremourning** [comment]
Eclim... Shrug. Its main problem is that it relies on eclipse (I realise that is the point)...  I use it and it works well, but I would rather not have to ever engage with or start eclipse. Or have to play config/project gymnastics. 

Compared to YCM's other engines, it's a massive pain to set up and make work. But it sounds like this language server won't be any better. And won't be any better sandboxed/bundled (which is our approach to minimal user config). 

Javacomplete2 requires less set up, but isn't as sophisticated as JDT/eclipse. I've had at best mixed experience with it personally. 

There are other java/Scala solutions, but I think one that requires basically 0 setup would be ideal. (Like even if it reads .project and .classpath, but doesn't require an eclipse instance for example, though ideally avoiding eve  this level of setup)

I'm all for java support in YCM, but I feel like we should only invest if it fits with our ethos. We're not even super happy with tern requiring a separate config, but at least we can bundle the whole thing and sort of contain it. If java support requires installing and configuring eclipse and its foibles, I'm not super excited about the advantage over eclim's omnifunc.

**Comment by icholy** [comment]
My idea is that there is a generic language server completer. Advanced users can configure it to any compatible server they want to.

**Comment by puremourning** [comment]
Ycmd architecture doesn't easily lend itself to that approach presently. Not to say it isn't a neat idea of course!

**Comment by Valloric** [comment]
> If java support requires installing and configuring eclipse and its foibles, I'm not super excited about the advantage over eclim's omnifunc.

We're not merging anything that requires installing eclipse. That's just not happening. So no need to worry.

> My idea is that there is a generic language server completer. Advanced users can configure it to any compatible server they want to.

Unless a specific use-case is being addressed, I don't see this being widely useful enough to be implemented.

Any java backend will need to be as easy to configure as the rest of YCM. We don't even like having the `ycm_extra_conf.py` stuff for C-family projects and we _really_ don't like the custom tern config. Asking users to install eclipse or other engines manually and out-of-band? Not something I'd be willing to merge.

**Comment by vheon** [comment]
I hope I wasn't wrong regarding installing Eclipse first 😝 

> Or have to play config/project gymnastics.

That is what I hate the most of the eclim experience, even though is the only way I can actually use eclipse.

> I'm saying we let ycmd be a client of the language-server-protocol instead of the other way around.

That is actually an idea that on one hand I personally like because could bring to all ycmd users other semantic engines that vs-code support that we don't (even though I'm not aware of any right now) but on the other hand I think that:

- ycmd_client -> ycmd -> language-server-protocol_server -> ycmd -> ycmd_client could be a little too complex and fragile.
- how complicated would be to set up a language-server-protocol_server? or will vs-code be enough?

**Comment by icholy** [comment]
@vheon  https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations

**Comment by icholy** [comment]
[Rust's language server](https://internals.rust-lang.org/t/introducing-rust-language-server-source-release/4209) have also adopted the LSP.

**Comment by vheon** [comment]
@icholy I didn't even know Rust had its own Language Server. @jwilm do you know how does it compare to racer?

**Comment by icholy** [comment]
@vheon It's very very new, not production ready. My intention is to show that the language server protocol is gaining traction and ycmd should support it.

**Comment by jwilm** [comment]
@vheon it uses racer internally to provide more features. I was planning to add a completer for it this weekend :). I'm not sure that YCM actually supports everything that RLS does.

**Comment by icholy** [comment]
Here's a another candidate: https://github.com/georgewfraser/vscode-javac

**Comment by puremourning** [comment]
I have tried [`vscode-javac`](https://github.com/georgewfraser/vscode-javac) and [`eclipse.jdt.ls`](https://github.com/eclipse/eclipse.jdt.ls)

After some testing and exploration, i concluded that for [my very-much-work-in-progress java completer using Language Server Protocol](https://github.com/puremourning/YouCompleteMe/tree/language-server-java), eclipse.jdt.ls was superior.

While the java-based version is simple enough that it required little to get it working, it also suffers that the experience and feature set isn't at the level that most users would expect.

I initially intended to offer both, but decided this was a terrible idea.

**Comment by puremourning** [comment]
FWIW as this is ycmd, the ycmd branch is: https://github.com/puremourning/ycmd-1/tree/java-language-server

**Comment by vheon** [comment]
@puremourning just out of curiosity (no pressure here 😝 ) how much work do you think it needs to be production ready? I might start testing this since I think I will have to write a little Java code at work 😒

**Comment by puremourning** [comment]
A fair bit TBH. There are quite a few hacks and quite a few things that just don't work right. Like imports (i've seen this JDT behaviour in eclim too):

<img width="550" alt="screen shot 2017-04-10 at 21 58 19" src="https://cloud.githubusercontent.com/assets/10584846/24882408/ddfe68ee-1e38-11e7-99cf-b639668e9837.png">
<img width="629" alt="screen shot 2017-04-10 at 21 58 34" src="https://cloud.githubusercontent.com/assets/10584846/24882411/dfbeb436-1e38-11e7-9e4d-80b9a5bbe132.png">

See that it returns the whole import string, and that it adds annoying `.*;`. YCM doesn't handle this because it needs something like https://github.com/Valloric/YouCompleteMe/pull/2489 or we need to handle the common prefix in the client as a hack.

Anyway here's a summary of the current status:

### Standard features working:

[x] completions
[x] realtime diagnostics
[x] install from `build.py`
[x] basic language server management (`RestartServer`)
[x] detection of installation (optional installation)
[x] `YcmDebugInfo` and log files

### Standard features not working

[ ] import completion (as above, JDT is a pain for these)
[ ] GetType (throws an exception)
[ ] GoToDeclaration (jumps to wrong location :S)

### Standard features not yet implemented:

[ ] GetDoc
[ ] FixIt
[ ] GoTo
[ ] GoToReferences ("code lens")
[ ] Tests!

### Stretch goals:

[x] asyncronous messages from the server (startup progress `>_<`)
[ ] code outline
[ ] code navigation
[ ] highlighting (e.g. to work with @davits DyeVim)

### Things that come for free(TM) in theory:

[ ] basic eclipse project support (untested)
[x] pom.xml (maven) support (seems to work)
[ ] gradle project support (untested)

I'd truly appreciate any feedback you do have though!

It should install with `--all` or `--jdt-completer` and the branch is up to date with master now.

**Comment by IngoHeimbach** [comment]
@puremourning Is there any new status on the Language Server Protocol integration in ycmd? This feature would be really awesome for gaining Julia completion in YCM since there is a working [Julia server](https://github.com/JuliaEditorSupport/LanguageServer.jl).

**Comment by puremourning** [comment]
@IngoHeimbach work on the java completer is progressing (slowly). i've updated the support status  above.

language server protocol implementation is inline with the features needed for that, but is strictly independent of jdtls (i have working POC for clangd and a different java server). Supports TCP and stdio communication.

**Comment by bstaletic** [comment]
@puremourning I may try your fork soon. Just a few questions.

> [X] GetType (throws an exception)

Is it done or does it still throw an error? 

Will you wait until you make the "strtch goals" work before making a PR or will you be posting (fingers crossed) a PR once you finish the "Standard features not yet implemented"?

P.S. I may decide to help you with the implementation/tests. But not promising anything.

**Comment by puremourning** [comment]
@bstaletic cool!

I fixed the comment - `GetType` should work without an exception.

Stretch goals won't be in any initial PR (it's already too big TBH) unless they are necessary to make some basic functionality work properly (such as async diags, post-complete-fixits)

For ref, you'll need:

* [ycmd branch](https://github.com/puremourning/ycmd-1/tree/java-language-server)
* [YCM branch](https://github.com/puremourning/YouCompleteMe/tree/language-server-java)
* `--jdt-completer` flag on `install.py`/`build.py`
* Some patience maybe :)

If you use syntastic, I would *strongly* recommend disabling it for Java. It's not only dog slow, but it can interfere with the diags in the current patchset. I tried to disable it programmatically, but last I checked it didn't work properly.

Note: don't be tempted to try it out on the `eclipse.jdt.ls` code itself - it doesn't actually work for its own code (for reasons that I don't really understand, but i don't grok eclipse, so that's normal)

**Comment by bstaletic** [comment]
Okay, thanks.
The pull request is huge. Have you thought about splitting it into language server part and java part?
Also the "standard features no yet implemented" are non essential. Would you consider making a pull request without those? I'm only asking because this will be a pain to review.

**Comment by puremourning** [comment]
Yes, when it is finalised (it's still evolving now), i will split it into reviewable pieces (to the extent that is possible)

**Comment by puremourning** [comment]
project status tracking here. https://trello.com/b/Y6z8xag8/ycm-java-language-server

hoping to start pushing PRs soon. it's a big project and quite a lot of complex new stuff, so it's going to take a while!

**Comment by micbou** [comment]
Java support was added in PR https://github.com/Valloric/ycmd/pull/857.
