### ISSUE TITLE
build.py links to the wrong dynamic python library during installation

### ISSUE THREAD

**Issue by jmenashe** [Valloric/ycmd#518]
I recently forked this repository for my personal use and had to make an adjustment to the installation process. The final, working adjustment is [here](https://github.com/jmenashe/ycmd/commit/b15ffd00484402b6379d7e731b940ee9300515ad). A note made by @micbou on the [previous commit](https://github.com/jmenashe/ycmd/commit/c8be763ddc0e4a960ce68e96c0d06149041b9451) requested that I provide some details on the problem and my machine configuration.

My OS is Ubuntu 14.04 64-bit. I don't recall the exact python version that was found by the `build.py` script but essentially it found a debug version of the dynamic library `libpython2.7.so`. Since I use the release version of Python 2.7 as my interpreter, I needed the script to instead use the release version of `libpython2.7.so`. Linking against the wrong version would cause the YCM server to crash immediately upon launching vim without providing any logging output, as would be expected with a link error. The modification I made in [this commit](https://github.com/jmenashe/ycmd/commit/b15ffd00484402b6379d7e731b940ee9300515ad) enabled the build script to find the release version of the dynamic library in what I consider to be a reasonably robust manner.

I hope this information is helpful but let me know if I can provide more details. Thank you for putting together this wonderful library!

**Comment by micbou** [comment]
Thanks for reporting the issue. I tried the script on one of my machine with Ubuntu 14.04 LTS 64-bit installed and it found this Python library:
```
/usr/lib/x86_64-linux-gnu/libpython2.7.so
```
which is not the debug version of the Python library (at least on my machine).

I am rather surprised that it found the debug version on your machine because its name should be `libpython2.7_d.so` (with the `_d` suffix) and the script only search for `libpython2.7.so`.

Could you try the script without your change and give us the Python library path it found? This would be really helpful.

**Comment by jmenashe** [comment]
The file it linked to is `/usr/lib/debug/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0`. This is from the `python2.7-dbg` package.

**Comment by micbou** [comment]
I see. I am updating the script with a combination of your approach (using `LIBPL` variable) and the old one (using `get_python_lib( standard_lib = True )`) because the folder returned by `LIBPL` does not contain a dynamic Python library on [pyenv](https://github.com/yyuu/pyenv). You can see the changes in PR #519. Though I successfully tested these changes on several configurations, it would be great if you could try them too and report the result here.
