### ISSUE TITLE
Can not link against boost_python3

### ISSUE THREAD

**Issue by bstaletic** [Valloric/ycmd#561]
Hello,

I'm having trouble compiling using my system's boost and python3. The command I'm using to generate Makefile is `cmake . ~/.vim/pack/ycm/opt/YouCompleteMe/third_party/ycmd/cpp -DUSE_SYSTEM_BOOST=ON -DUSE_SYSTEM_LIBCLANG=ON -DUSE_PYTHON2=OFF`. The result: cmake complains it can't find boost_python3. If I ommit either `-DUSE_PYTHON2=OFF` or `-DUSE_SYSTEM_BOOST` it goes perfectly.

Cmake output with my desired command:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Your C++ compiler supports C++11, compiling in that mode.
-- Found PythonLibs: /usr/lib64/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3.3") 
Using libclang to provide semantic completion for C/C++/ObjC
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1468 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  ycm/CMakeLists.txt:202 (find_package)


CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1794 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.61.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python3

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  ycm/CMakeLists.txt:202 (find_package)


Using external libclang: /usr/lib64/libclang.so.3.8
-- Found PythonInterp: /usr/bin/python3.5 (found version "3.5.2") 
-- Configuring incomplete, errors occurred!
See also "/home/bstaletic/ycmd/CMakeFiles/CMakeOutput.log".
See also "/home/bstaletic/ycmd/CMakeFiles/CMakeError.log".
```

However, if I ask for python-3.5 component of boost cmake successfully finds it. I also tried asking cmake to find python-3 component but that failed with thte same message.

My boost version is 1.61, compiled with both python2 and python3 support and my cmake version is 3.6.1. I'm running Gentoo amd64 (unstable branch). More details about my system can be found [here](https://forums.gentoo.org/viewtopic-t-1048838-highlight-.html).

**Comment by puremourning** [comment]
I guess this is because of this change:

https://github.com/Valloric/ycmd/pull/537

We don't really support using system boost (there really is *no* point). Just don't supply -DUSE_SYSTEM_BOOST and you'll be fine.

**Comment by yan12125** [comment]
@bstaletic How is boost built on Gentoo? Is there anything like a build script?

**Comment by bstaletic** [comment]
@puremourning I know it is unsupported, I just hoped someone would take a look.
@yan12125 It done using a source based package manager named portage. It's fairly similar to Arch's abs/makepkg. It provides you USE flags you can set to enable/disable components of a package and the file portage parses is called "ebuild".

Ebuild of the gentoo's boost package can be found here:
http://data.gpo.zugaina.org/gentoo/dev-libs/boost/

The files dir contains patches gentoo applies to the boost package. I'll be glad to answer any further question regarding gentoo's build system.

**Comment by yan12125** [comment]
Thanks for that. I'll have to try to install a Gentoo VM first :)

**Comment by yan12125** [comment]
Is there a prebuilt tarball for Gentoo? I'm too lazy to install a VM and build boost on it.

**Comment by bstaletic** [comment]
Try to look for stage4 tarballs. Stage3 is the generic base system and is used for installing Gentoo. Stage4 is a completely usable system, kind of like something you get when you install distro like ubuntu.

Stage4 tarballs are not official way of installing gentoo but they are availle on some repos. I never used stage4 I did not create so I have no idea what's in those on gentoo mirrors. Also I would have supplied a stage4 if I were close to my pc.

**Comment by yan12125** [comment]
Finally built boost with Python 3.5. There's only ```/usr/lib64/libboost_python-3.5.so```. Does ycmd work with system boost and Python 3 before 9b51b397d4ee595e7179f2f3d98820a54139bfc7?

I guess the cause is that the ebuild file passes ```--python-buildid``` flag to boost. The result is that the Boost.Python library can have an arbitrary name. I guess Gentoo instead of ycmd should solve this problem as it's not a general Boost scenario but a distro-specific one.

**Comment by ff2000** [comment]
For me it fails to build with (system default) python-3.4 since 9b51b39, before everything was OK.
Gentoo allows parallel installation of different python3-versions (python-3.4 and python-3.5 for example). That won't change. Therefore "python3" boost module never will be found as well as "python-3".

AFAICS this commit tries to enable Distros that still use python2 as their default python implementation to work with python3, is that correct? Do those Distros append version for lib(boost_)python-2.7? And what about python2-support for distros that already default to python3?

**Comment by puremourning** [comment]
Everyone: our advice is not to use --system-boost. Honestly as far as we know there is no good reason to do so. YCM ships a subset of boost that it uses and statically links it. That's what we test, and that's what we support. 

Am I missing something? Why would you want to use an unsupported and untested option that we only had for BSD compatibility? Is there some nuance that means you need to use this feature? If so, then it would really help us if we could understand it. 

Thanks,
Ben

**Comment by ff2000** [comment]
On Thu, 04 Aug 2016 00:22:25 -0700, Ben Jackson <notifications@github.com> wrote:
> Everyone: our advice is not to use --system-boost. Honestly as far as we know there is no good reason to do so. YCM ships a subset of boost that it uses and statically links it. That's what we test, and that's what we support. 
> 
> Am I missing something? Why would you want to use an unsupported and untested option that we only had for BSD compatibility? Is there some nuance that means you need to use this feature? If so, then it would really help us if we could understand it. 

For me No.1 is build time: Boost Python is quite heavy for me, especially on Memory. I have to close my Browser Window and possibly other applications to get as much free memory as possible to avoid unnecessary swapping. If it starts swapping I have no chance to use the laptop for 15-20 minutes. (As a side-effect running apps lose their cache, e.g. my mail program).
I won't go into bundled libraries as YouCopleteMe is extreme on that - but this also plays a role.

> 
> Thanks,
> Ben
> 
> > On 4 Aug 2016, at 07:05, ff2000 <notifications@github.com> wrote:
> > 
> > For me it fails to build with (system default) python-3.4 since 9b51b39, before everything was OK.
> > Gentoo allows parallel installation of different python3-versions (python-3.4 and python-3.5 for example). That won't change. Therefore "python3" boost module never will be found as well as "python-3".
> > 
> > AFAICS this commit tries to enable Distros that still use python2 as their default python implementation to work with python3, is that correct? Do those Distros append version for lib(boost_)python-2.7? And what about python2-support for distros that already default to python3?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> 
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Valloric/ycmd/issues/561#issuecomment-237473574
> 
--

**Comment by puremourning** [comment]
Interesting. Thanks. 

How often do you compile ycmd? As a dev I do it frequently, but I like to think that users do t compile it that often. ^_^

**Comment by yan12125** [comment]
@ff2000 @bstaletic Seems you have enabled additional emerge keywords for boost? Are you doing the same for cmake? I'd like to know what's your cmake version.

**Comment by ff2000** [comment]
@yan12125 I have just enabled ~amd64 keyword for both boost and cmake. I run boost-1.61.0 and cmake-3.6.1.

@puremourning It's not that often, but I usually update my vim-plugins at least once a week (using junegunn/vim-plug) and I hit at least once a month a non-usable system-state because of swapping. Not building boost but using system-boost (and system-clang as it does not extract the clang-tarball into the builddir which is on tmpfs-mounted /tmp and so uses another ~900MB of my RAM) solved the issue, so I went that route.
BUT... this issue really bugs me, so I think of changing my mind and use bundled boost and not auto-update ycm through Plug but do all by hand. Or emerge ycm through portage where I can easily patch (e.g. sed) on-the-fly. Let's see.

**Comment by puremourning** [comment]
The other option is to only recompile YCM when it tells you that you need to.

**Comment by ff2000** [comment]
On Fri, 05 Aug 2016 00:39:59 -0700, Ben Jackson <notifications@github.com> wrote:
> The other option is to only recompile YCM when it tells you that you need to. 

... and still use Plug to update ycm?
That's not an option as it again might trigger rebuild requests at any point with issues like swapping or stopping running applications to free memory.
Or use a different completion engine while ycm is broken until I have time for a rebuild...

**Comment by yan12125** [comment]
OK. There's also a [magic patch](http://ftp.twaren.net/Linux/Gentoo/gentoo-portage/dev-util/cmake/files/cmake-2.8.12.2-FindBoost-python.patch) in Gentoo's cmake. With that patch, ```find_package(Boost COMPONENTS python)``` finds a ```libboost_python``` version corresponding to the default Python interpreter version. It's totally Gentoo's magic, so my idea is still that Gentoo needs to be fixed.

Here I want to clarify what @ff2000 mentioned at https://github.com/Valloric/ycmd/issues/561#issuecomment-237460874:

> this commit tries to enable Distros that still use python2 as their default python implementation to work with python3, is that correct?

It's incorrect. Take Arch Linux for example. Arch Linux has Python 3 as the default Python interpreter since [6 years ago](https://www.archlinux.org/news/python-is-now-python-3/). On the other hand, Arch's [Boost package](https://www.archlinux.org/packages/extra/x86_64/boost-libs/files/) has ```libboost_python.so``` and ```libboost_python3.so```, which links to Python 2.7 and Python 3.5, respectively. According to the [Jamfile](http://svn.boost.org/svn/boost/trunk/libs/python/build/Jamfile.v2) of Boost.Python, Boost installs the Python 2 version of libboost_python as ```libboost_python.so``` and the Python 3 version as ```libboost_python3.so```. (See the last few lines in the aforementioned Jamfile) Above all, it's Boost.org that uses Python 2 as the default, but not individual distributions.

For Gentoo, there's another patch that [disables libboost_python3.so](http://ftp.twaren.net/Linux/Gentoo/gentoo-portage/dev-libs/boost/files/boost-1.48.0-disable_libboost_python3.patch), so ```libboost_python3.so``` never appears on Gentoo. As a result my commit in ycmd breaks Gentoo users.

Gentoo should find a Python3-compatible libboost_python if ```find_package(Boost COMPONENTS python3)``` is used. Maybe submitting a bug to Gentoo's bug tracker is the way. Do you know where I should go if there's a bug in Gentoo's portage tree? @ff2000 @bstaletic

**Comment by micbou** [comment]
> That's not an option as it again might trigger rebuild requests at any point with issues like swapping or stopping running applications to free memory.

Rebuild requests? What do you mean? Most of the time, only the Python code will change when updating YCM so there is no need to rebuild anything.

**Comment by vheon** [comment]
I use vim-plug as well but I rebuild only when necessary... basically I have this in my `vimrc`:

````viml
Plug 'Valloric/YouCompleteMe', { 'do': function('startup#YCMInstall') }
```

and this in `autoload/startup.vim`:

```viml
function! startup#YCMInstall(info)
  if a:info.status == 'installed' || a:info.force
    !./install.sh --clang-completer --gocode-completer
  endif
endfunction
```

So I update YCM with `:PlugUpdate` and since most of the time we only touch Python code you don't have to rebuild anything. When the time comes that we touch the C++ side and a rebuild is needed I get the error on vim startup saying that I have to rebuild, then I use `:PlugUpdate! YouCompleteMe` (notice the `!`) and then a re-build is issued.

**Comment by puremourning** [comment]
Nice! FAQ entry?

**Comment by vheon** [comment]
I believe this is already in the vim-plug wiki, but sure we could add a FAQ entry in our doc ;) I'll see if I can do it tomorrow 👍

**Comment by ff2000** [comment]
@vheon that's exactly what I meant with "let vim-plug update YCM and react on rebuild requests". As already stated that's not an option as I have no control over when the rebuild has to happen.

@yan12125 You can open issues on https://bugs.gentoo.org

I had another look at boost/cmake and tried to get what can be expected. I am no expert and can only try to understand what happens.
* FindBoost.cmake seems to not have any reliable way to detect boost_python for python2 or python3. In the dependencies for other components only "python" gets referenced - E.g. for mpi_python it simply states `set(_Boost_MPI_PYTHON_DEPENDENCIES python mpi serialization)`
* It looks to me that boost_python3 only gets found because it hijacks the logic in FindBoost.cmake. You even get a warning that Boost_PYTHON3_HEADERS is not found (there is no python3.hpp but only python.hpp)
* When I build boost_python (as released upstream) only with python3 I get both boost_python and boost_python3 targets with both being identical. So the assumption that boost_python is the python2-version is wrong and only true for certain distros.
* I found the Calamares project which simply added its own logic to [find BoostPython3](https://github.com/calamares/calamares/blob/master/CMakeModules/BoostPython3.cmake)

In the meantime I will just use a hack to force boost_python3 do the right thing:

```
EXTRA_CMAKE_ARGS="-DBoost_PYTHON3_FOUND=1 -DBoost_PYTHON3_LIBRARY_RELEASE=/usr/lib64/libboost_python-3.4.so" python3.4 ./install.py --clang-completer --system-libclang --system-boost 
```

**Comment by yan12125** [comment]
@ff2000 You're right Boost.Python + CMake is messy. I think it's Boost that should be fixed instead of CMake. Proposed at boostorg/python#82.

**Comment by ff2000** [comment]
@yan12125 Thx for the links and your report. Let's see how this all turns out, the PR at CMake got closed for now...

**Comment by lilred** [comment]
>Am I missing something? Why would you want to use an unsupported and untested option that we only had for BSD compatibility? Is there some nuance that means you need to use this feature? If so, then it would really help us if we could understand it.

YouCompleteMe takes a million years to build, and often fails late in the process. Sometimes it even "misbuilds" and you have to start over. For example, if my Vim is compiled with Python3 support but /usr/bin/python is Python2 (**as is default on, for example, Ubuntu 16.04**), then `./install.py` will work perfectly fine and then `ycmd` will just crash when you try to use it.

Build artifacts aren't cached, so after you fix a build failure you have to rebuild from scratch. Going from zero to a fully-working YouCompleteMe install usually takes me an entire afternoon or more.

Because of that, I'm looking for ways to cut down on the build time. Using the system clang and system boost sounded like promising ways to do that, but apparently that's broken (something the documentation is less than upfront about).

>How often do you compile ycmd? As a dev I do it frequently, but I like to think that users do t compile it that often. ^_^

Every time I start working on a new system, which was maybe 7 times this year. About 4-5 work days wasted on this.

____________________

YouCompleteMe is the Vim package I love to hate. The concept fills an important hole in the Vim landscape, and the core use case is amazing, but installation is death by a thousand cuts, startup is dog slow, etc. Everyday I'm a bit closer to forking it.

I'm really 95% grateful and 5% exasperated - you guys are clearly capable of writing amazing software, YCM is proof of that. So why is the low-hanging stuff neglected? Things like incremental builds, etc. shouldn't be too hard to pull off. :(

**Comment by vheon** [comment]
> . For example, if my Vim is compiled with Python3 support but /usr/bin/python is Python2 (as is default on, for example, Ubuntu 16.04), then ./install.py will work perfectly fine and then ycmd will just crash when you try to use it.

Yes it will crash, with an error like the one specified at https://github.com/Valloric/YouCompleteMe#i-get-importerror-exceptions-that-mention-pyinit_ycm_core-or-initycm_core (the proper solution to the problem is there). YCM is perfectly capable to run in vim with Python3 while the server was built with Python2 or even a different Python3 binary, you only have to tell it where it is.

> Using the system clang and system boost sounded like promising ways to do that, but apparently that's broken 

The reason that is broken is because we test with a specific version of Boost and would be crazy to support every single version of it. 

> So why is the low-hanging stuff neglected? Things like incremental builds, etc. shouldn't be too hard to pull off. :(

As always, software is about compromise :) There is no way to make everyone happy. I'm not saying that what you're asking is not doable or worth doing or that it will never land here but I can assure you that for one person that want to speed up the build (so keeping the intermediate build object on the disk) there are another one who would like for YCM to use less space.

**Comment by puremourning** [comment]
> YouCompleteMe takes a million years to build, and often fails late in the process. 

I'm sorry that's your experience. Our CI builds don't take quite that long, and they pretty much always succeed. I also build ycmd frequently and almost never have build failures (unless I just caused them!) 

> Sometimes it even "misbuilds" and you have to start over. 

I'm sorry I have no idea what this means. I think the only common problem that could be explained by this is that you end up linking against a python which was not built with `--enable-shared`. There's an FAQ about this. Not sure i can really help more without any further information.

> For example, if my Vim is compiled with Python3 support but /usr/bin/python is Python2 (as is default on, for example, Ubuntu 16.04), then ./install.py will work perfectly fine and then ycmd will just crash when you try to use it.

I don't actually think that is true anymore. We have gone to great lengths to separate the python code that runs in Vim and the python code that runs in the server. In particular, Vim client no longer loads the `ycm_core.so` DLL so YCM is fully compatible with Vim compiled with Python 3 and the server built and executed with python 2. We even go so far as to record the python interpreter used when building the server and using it when booting ycmd. If you're still having these problems, then please see CONTRIBUTING.md and raise a fully qualified issue report.

> Build artifacts aren't cached, so after you fix a build failure you have to rebuild from scratch. Going from zero to a fully-working YouCompleteMe install usually takes me an entire afternoon or more.

Again, I'm sorry that is your experience. It usually takes me ~5 minutes. Be aware that if you want to cache the build artefacts, you can follow the Full Installation Instructions (carefully read README.md) or you can investigate some of the developer-oriented options to `install.py` (such as `--build-dir`). These options aren't documented (other than in `install.py --help`) as they are intended for ycmd developers primarily.

> Because of that, I'm looking for ways to cut down on the build time. Using the system clang and system boost sounded like promising ways to do that, but apparently that's broken (something the documentation is less than upfront about).

It's not broken per-se, but we cannot test every version of every library, because we don't have the resources to test it. We bundle because we can control what does and does not work together.

> Every time I start working on a new system, which was maybe 7 times this year. About 4-5 work days wasted on this.

Not much to add here, other than trying to understand why this is taking so long,. The build takes about 10 mins on moderate hardare. We know that the submodule checkout is quite large and that can be frustrating. Are you hitting dependency problems? What causes you to spend so much time?

Maybe you'd like to look at our vagrant file, which takes a system from 0 to fully built ycmd in effectively one go (including al features and dependencies and multiple python versions).

> YouCompleteMe is the Vim package I love to hate. The concept fills an important hole in the Vim landscape, and the implementation of the core use case is an absolute delight, but 

> installation is death by a thousand cuts, 

For me, it is a single command.

> startup is dog slow, kingdom of WONTFIX, 

We'd love to improve startup time. Most of it is starting the Python interpreter. It's not a matter of WONTFIX, it's a matter of DONTKNOWHOWTOFIXPRSWELCOME.

> Everyday I'm a bit closer to forking it.

PRs are always welcome. This is a community project manned by (passionate) volunteers.

> I'm really 95% grateful and 5% exasperated - 

That's good to hear. Forgive us if we feel your message is 95% complaint and 5% other.

> you guys are clearly capable of writing amazing software,

Heh, some of us even get paid for it in another world.

> So why is the low-hanging stuff neglected? 

As mentioned above, i really don't think there are low hanging fruit here. Certainly if there were I'm sure the team would work on them. Or maybe some kind member of the community which has a vested interest in harvesting such ripe goodies.

> Things like incremental builds, etc. shouldn't be too hard to pull off. :(

Quite. README.me shows that it is totally possible. I use it all the time.

**Comment by lilred** [comment]
>>For example, if my Vim is compiled with Python3 support but /usr/bin/python is Python2 (as is default on, for example, Ubuntu 16.04), then ./install.py will work perfectly fine and then ycmd will just crash when you try to use it.

>I don't actually think that is true anymore.

It literally happened to me today :(

>It's not broken per-se, but we cannot test every version of every library, because we don't have the resources to test it.

It *is* broken, though. See: this issue. I don't even really mind that it's broken, shit just happens; but the issue being closed without a resolution stings a bit.

>>Things like incremental builds, etc. shouldn't be too hard to pull off. :(

>Quite. README.me shows that it is totally possible. I use it all the time.

\>C-f "incremental"
\>0 results

**Comment by yan12125** [comment]
This issue is indeed a bug, but it's boost that should be blamed instead of YCM. If anyone can finish my partial PR at https://github.com/boostorg/python/pull/83, everything will be fine. I didn't continue it as I can't understand Boost.Build's mysterious build scripts.

**Comment by puremourning** [comment]
@lilred 

> Be aware that if you want to cache the build artefacts, you can follow the Full Installation Instructions (carefully read README.md) or you can investigate some of the developer-oriented options to install.py (such as --build-dir). These options aren't documented (other than in install.py --help) as they are intended for ycmd developers primarily.

**Comment by puremourning** [comment]
@lilred 

> It literally happened to me today :(

That's disappointing. Perhpas you could file a complete issue report fopllowing the instructions in `CONTRIBUTING.md` so that we can debug it. This thread is not related to such issues (rather a Boost bug which causes a build failure with ycmd).

**Comment by puremourning** [comment]
@lilred FYI here is a commit in my fork which adds an incremental build https://github.com/puremourning/ycmd-1/commit/957e6db71ef21f73c8e3f5b34128d4dfcb058efb

**Comment by archenroot** [comment]
Did someone fixed this for Gentoo or maybe in the CMAKE FindBoost.cmake file?

i am stil facing not with this package ycmd, but other build using CMAKE builtin FindBoost.cmake file:
```
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1527 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1853 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python3

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)

```

Thanks for comments.

**Comment by o01eg** [comment]
@archenroot It possible to manually set cmake variables for boost's python library.
You could look there https://bugs.gentoo.org/show_bug.cgi?id=586776
