### ISSUE TITLE
YouCompleteMe unavailable: requires Vim compiled with Python 2.x support

### ISSUE THREAD

**Issue by malreynolds** [Valloric/ycmd#587]
Hi,

It is my understanding that I should be able to run YouCompleteMe from Vim with python3 support.

`vim --version` output contains `-python` and `+python3`.

Output from `:echo has('python') || has('python3').` is `1`.

The module builds successfully by running `./install.py --clang-completer`, but once I startup vim, I get the following warning: 

> YouCompleteMe unavailable: requires Vim compiled with Python 2.x support

Am I misunderstanding the docs or is this a bug?

> Make sure you have Vim 7.3.598 with python2 **or** python3 support. 

Thanks.

**Comment by vheon** [comment]
First of all this looks like a problem you have with YouCompleteMe and not with ycmd. If the title is the error you get it then it means that you have a very old version of YouCompleteMe, because as you could see in the code https://github.com/Valloric/YouCompleteMe/blob/master/plugin/youcompleteme.vim#L36-L40 the message is different in the latest version.
