### ISSUE TITLE
Plug-in based architecture for completers

### ISSUE THREAD

**Issue by wincent** [Valloric/ycmd#669]
Have you ever thought about adding some kind of plug-in based architecture so that users could extend ycmd (add new completers) without having to integrate those changes directly into the ycmd repo?

For example, I have made a couple of custom completers to do some very specific things:

- Provide completion of email addresses via `lbdbq`, drawing from the macOS Contacts app, `mutt` aliases, and previously received emails, active in Vim in files of type `mail`, and triggered on lines in the header area (`To:`, `Cc:`, `From:`, `Reply-To:` etc).
- Provide completion of wiki article titles when typing links in Markdown documents in a Markdown-based wiki.

These are both so specific that they'd be unlikely to be of general interest, and so I wouldn't propose them as PRs to the ycmd repo. But it would be nice to be able to bundle them into plug-ins, register them with ycmd, and therefore not have to maintain a fork.

Thoughts? If this is something you're interested in I could try and help out with a PR (not a Python programmer, but I might be able to figure something out).

**Comment by Valloric** [comment]
> Have you ever thought about adding some kind of plug-in based architecture so that users could extend ycmd (add new completers) without having to integrate those changes directly into the ycmd repo?

We had exactly this for years. I removed it for the following two reasons:

1. The internal Completer API wasn't, isn't and will never be stable. It's too much of a burden on ycmd development; we want to be able to change that API willy-nilly (and have done so many times). With everything being in the ycmd repo, we can easily update all Completers to the new API. 
2. People developed their own generally useful Completers without upstreaming them because that's easier. People will rather avoid sending a PR if they can.

Removing the plugin API became a good forcing function for people to actually integrate their Completers into ycmd. Your use-case of "I have a Completer that you'll never want to merge but it's hard for me to maintain without plugins" is an unfortunate casualty; I sadly don't know of a way to support that without also making it too easy to not contribute a useful Completer to ycmd. :(

"This is why we can't have nice things" and all that...

**Comment by wincent** [comment]
Thanks for the explanation!

> I have a Completer that you'll never want to merge but it's hard for me to maintain without plugins

It's not actually that hard. YouCompleteMe and ycmd work just fine, and I feel no pressure to update my basically-year-old fork. It's easy enough to cherry-pick over specific bug fixes when I need them (have done it twice so far); there's no need for me to chase the bleeding edge.

Thanks once again for sharing your rationale.
