### ISSUE TITLE
Add ESLint diagnostic support to Tern (javascript) completer

### ISSUE THREAD

**Issue by nmschulte** [Valloric/ycmd#690]
There is a plugin for Tern that supports code linting (validation) via ESLint.  Is this something that the Tern completer could expose as diagnostics w/ ycmd / YouCompleteMe?

https://github.com/angelozerr/tern-eslint

---
https://github.com/angelozerr/tern-eslint/blob/master/eslint.js#L390
https://github.com/angelozerr/tern-eslint/blob/master/eslint.js#L404

**Comment by nmschulte** [comment]
Also, @angelozerr has a semantic analyzer plugin for Tern: https://github.com/angelozerr/tern-lint

**Comment by puremourning** [comment]
I actually implemented this a year or more ago. At the time the diagnostics were inferior to what syntastic provided, so I dropped it.

**Comment by nmschulte** [comment]
I could look into it again, though the plugin looks outdated and will need
some work (eslint).  Which were you referring to?

I am using Syntastic now.

**Comment by puremourning** [comment]
I was referring to @angelozerr plugins. It's  not hardness to implement and maybe it has improved since. It's also asynchronous and real-time. But personally my only use case uses jshint by policy and so I don't have a strong desire to revisit it. You may find it in my fork however if you want to go spelunking.

**Comment by micbou** [comment]
The way forward is to use the TypeScript completer for JavaScript which provides diagnostics. See PR https://github.com/Valloric/ycmd/pull/1036.
