### ISSUE TITLE
Substitute OmniSharpServer for omnisharp-roslyn

### ISSUE THREAD

**Issue by fatso83** [Valloric/ycmd#766]
Work has ended on OmniSharpServer in favor of [omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn). As #765 shows it no longer compiles without customization of `xbuild`, so maybe one should consider using the new kid in town?

I don't know about the effort involved, but would a PR be welcome?

**Comment by bstaletic** [comment]
There was a PR open for a long time now. We closed it as it didn't make much effort. Take a look at #287. Of course, if you can help, it would be much appreciated.

**Comment by mispencer** [comment]
#287 was closed in favor of https://github.com/Valloric/ycmd/pull/213, but that was incomplete as well.

**Comment by vheon** [comment]
As @mispencer said we closed #213 because it was not complete (and IIRC it wasn't a switch of backend but we were supporting both OmniSharpServer and omnisharp-roslyn and we weren't super happy about it, but I might remember wrong).

From the "core" team here none of us is a C# developer so you might imagine that there is not an effort from our end on this because but

>  but would a PR be welcome?

Absolutely! :+1:

**Comment by fatso83** [comment]
I see there is a whole history of changes here in the pr sections. I was just searching through the issue labels. From what I can see some of the basic problems in the roslyn version are yet to be fixed, so I guess any effort of mine here wouldn't make much of a difference, but the mentioned PRs shows where to go if one wants to help out.
