### ISSUE TITLE
Add a Hack completer

### ISSUE THREAD

**Issue by cweagans** [Valloric/ycmd#97]
For people working with Hack (Facebook's superset of PHP), it's nice to have autocomplete functionality. hhvm's typechecker provides this out of the box (`hh_client --auto-complete`). There's already a vim plugin that does this, but integrating with ycmd instead gets the functionality to more editors.

**Comment by Valloric** [comment]
I agree with this and would like to see a pull request for it. I don't see much point to having an issue open for this since nobody is committed to doing the work. We could also have issues like "add a completer for language X" for every programming language out there and it wouldn't make much sense unless there was actual intent to go and build it.

So I'll close this for now; pull requests adding Hack support are welcome, but I don't see myself personally implementing this.

**Comment by cweagans** [comment]
I'm working on this right now, actually.

I have a question for you, if you don't mind: Hack and PHP both use the same file extension (.php), but Hack files start with `<?hh` instead of `<?php`. Is there some way of telling a completer not to activate unless the file starts with `<?hh`?

**Comment by Valloric** [comment]
ycmd doesn't care about the extension; the JSON request will have the filetype of the code that's supposed to be completed. So for Hack files, the filetype should be `hack`, and for PHP files it should be `php`.

In other words, differentiating between the two is a client-side issue, not a server-side one.

**Comment by cweagans** [comment]
Ah, got it. That makes much more sense!

**Comment by micbou** [comment]
Hack is too niche to be included and maintained in ycmd. Closing.
