### ISSUE TITLE
C++: ycmd does not show protected members

### ISSUE THREAD

**Issue by Xoltus** [Valloric/ycmd#980]
Hi everyone,

I noticed ycmd does not offer any completion for protected members when implementing a derived class.
For instance,

class Base {
protected:
    int m_protected;
};

class Derived: public Base {
public:
    void function(){
      this-> // m_protected does not show up
    }
};

Even though this seems to be a bug in clang [1], maybe anyone knows a workaround such that all possible (even private) members are shown.

Cheers,
Kevin

[1] https://bugs.llvm.org/show_bug.cgi?id=24329

**Comment by micbou** [comment]
Surprising this issue hasn't yet been fixed in libclang. Is it that uncommon to use protected members in derived classes in C++?

> Even though this seems to be a bug in clang [1], maybe anyone knows a workaround such that all possible (even private) members are shown.

You could comment [these lines](https://github.com/Valloric/ycmd/blob/2f5474b42e27416cf3bf85d3df616d1dc5d4f1d8/cpp/ycm/ClangCompleter/ClangHelpers.cpp#L228-L230) and recompile ycmd.

**Comment by Xoltus** [comment]
I use protected members all the time, hence, I prefer ycmd to list all members instead of not showing protected ones.
Anyhow, I am happy to confirm that removing these lines works.

Thank you
